// sveltekit/src/lib/components/bundles/BundleCard.svelte
<script lang="ts">
	import type { Product } from '$lib/types';

	export let product: Product;
	export let requiredQuantity: number;
	export let discountPercentage: number;
	export let locale: 'sv' | 'en' = 'sv';
</script>

<a href="/products/{product.id}" class="group block bg-white dark:bg-[#2a3330] rounded-2xl overflow-hidden shadow-soft hover:shadow-xl transition-all duration-300 hover:-translate-y-1">
	<div class="p-6">
		<div class="flex items-center gap-2 mb-3">
			<span class="px-3 py-1 bg-sage-100 dark:bg-sage-900/30 text-sage-700 dark:text-sage-300 rounded-full text-sm font-medium">
				{locale === 'sv' ? 'Spara' : 'Save'} {discountPercentage}%
			</span>
		</div>
		<h3 class="text-lg font-semibold text-forest-800 dark:text-[#E8EDE8] mb-2">
			{product.translations[locale]?.name ?? product.name}
		</h3>
		<p class="text-forest-600 dark:text-[#B8C5B8] text-sm mb-4">
			{locale === 'sv' ? `Välj ${requiredQuantity} oljor` : `Choose ${requiredQuantity} oils`}
		</p>
		<div class="flex items-baseline gap-2">
			<span class="text-2xl font-bold text-forest-800 dark:text-[#E8EDE8]">
				{new Intl.NumberFormat(locale === 'sv' ? 'sv-SE' : 'en-US', { style: 'currency', currency: 'SEK' }).format(product.price)}
			</span>
		</div>
		<button class="mt-4 w-full py-2.5 bg-sage-600 hover:bg-sage-700 text-white rounded-full font-medium transition-colors">
			{locale === 'sv' ? 'Välj oljor' : 'Select oils'}
		</button>
	</div>
</a>

// src/components/bundles/BundleCard.tsx
'use client';

import Link from 'next/link';
import { Product } from '@/types';
import { BundleImage } from './BundleImage';
import { TagIcon, CheckIcon, ArrowRightIcon } from '@heroicons/react/24/outline';

interface BundleCardProps {
  product: Product;
  requiredQuantity: number;
  discountPercentage: number;
  locale?: 'sv' | 'en';
}

export function BundleCard({
  product,
  requiredQuantity,
  discountPercentage,
  locale = 'sv',
}: BundleCardProps) {
  const regularPrice = 89 * requiredQuantity;
  const savings = regularPrice - product.price;

  return (
    <Link
      href={`/products/${product.id}`}
      className="group block bg-white dark:bg-[#242a28] rounded-xl border-2 border-sage-200 dark:border-[#3f4946] hover:border-sage-400 dark:hover:border-sage-600 shadow-sm hover:shadow-lg transition-all duration-300 overflow-hidden"
    >
      {/* Badge */}
      <div className="relative">
        <div className="absolute top-3 right-3 z-10 bg-gradient-to-r from-sage-600 to-forest-600 text-white px-3 py-1 rounded-full text-sm font-bold shadow-md">
          {locale === 'sv' ? 'SPARA' : 'SAVE'} {savings} kr
        </div>

        {/* Image - Layered Lavender bottles */}
        <div className="relative w-full aspect-square bg-gradient-to-br from-sage-50 to-forest-50 flex items-center justify-center p-8">
          <div className="group-hover:scale-105 transition-transform duration-300">
            <BundleImage quantity={requiredQuantity} />
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="p-5">
        {/* Title */}
        <h3 className="text-xl font-serif font-bold text-forest-800 dark:text-[#E8EDE8] mb-2 group-hover:text-sage-700 dark:group-hover:text-sage-400 transition-colors">
          {locale === 'sv' ? product.translations.sv.name : product.translations.en.name}
        </h3>

        {/* Description */}
        <p className="text-sm text-forest-600 dark:text-[#B8C5B8] mb-4 line-clamp-2">
          {locale === 'sv' ? product.translations.sv.description : product.translations.en.description}
        </p>

        {/* Pricing */}
        <div className="flex items-baseline gap-2 mb-3">
          <span className="text-3xl font-bold text-forest-900 dark:text-[#E8EDE8]">
            {product.price} kr
          </span>
          <span className="text-lg text-forest-500 dark:text-[#6B7B6B] line-through">
            {regularPrice} kr
          </span>
        </div>

        {/* Discount Badge */}
        <div className="inline-flex items-center gap-2 bg-sage-100 dark:bg-[#2a3330] text-sage-800 dark:text-sage-400 px-3 py-1 rounded-full text-sm font-semibold mb-4">
          <TagIcon className="w-4 h-4" />
          {discountPercentage.toFixed(0)}%{' '}
          {locale === 'sv' ? 'rabatt' : 'off'}
        </div>

        {/* Features */}
        <div className="space-y-2 mb-4">
          <div className="flex items-center gap-2 text-sm text-forest-700 dark:text-[#C5D4C5]">
            <CheckIcon className="w-5 h-5 text-sage-600 flex-shrink-0" />
            <span>
              {requiredQuantity}x {locale === 'sv' ? 'Lavendel Eterisk Olja' : 'Lavender Essential Oil'}
            </span>
          </div>
          <div className="flex items-center gap-2 text-sm text-forest-700 dark:text-[#C5D4C5]">
            <CheckIcon className="w-5 h-5 text-sage-600 flex-shrink-0" />
            <span>
              {locale === 'sv'
                ? '10ml vardera, premium kvalitet'
                : '10ml each, premium quality'}
            </span>
          </div>
          <div className="flex items-center gap-2 text-sm text-forest-700 dark:text-[#C5D4C5]">
            <CheckIcon className="w-5 h-5 text-sage-600 flex-shrink-0" />
            <span>
              {locale === 'sv'
                ? 'Spara mer ju fler du köper'
                : 'Save more when you buy more'}
            </span>
          </div>
        </div>

        {/* CTA */}
        <div className="flex items-center justify-between pt-4 border-t border-cream-200 dark:border-[#3f4946]">
          <span className="text-sm font-medium text-sage-700 dark:text-sage-400">
            {locale === 'sv' ? 'Bygg din egen' : 'Build your own'}
          </span>
          <ArrowRightIcon className="w-5 h-5 text-sage-600 group-hover:translate-x-1 transition-transform" />
        </div>
      </div>
    </Link>
  );
}
