// sveltekit/src/routes/admin/products/[id]/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { page } from '$app/stores';
	import { goto } from '$app/navigation';
	import { toast } from '$lib/stores/toast';
	import Toast from '$lib/components/ui/Toast.svelte';
	import { ArrowLeft, Trash2 } from 'lucide-svelte';

	const CATEGORIES = [
		{ value: 'essential-oils', label: 'Essential Oils' }, { value: 'carrier-oils', label: 'Carrier Oils' },
		{ value: 'diffusers', label: 'Diffusers' }, { value: 'accessories', label: 'Accessories' },
		{ value: 'gift-sets', label: 'Gift Sets' }, { value: 'bundles', label: 'Bundles' },
	];

	$: id = $page.params.id;
	let loading = true;
	let saving = false;
	let deleting = false;
	let deleteConfirm = false;
	let form = { nameSv: '', descriptionSv: '', nameEn: '', descriptionEn: '', price: '', sku: '', category: 'essential-oils', weight: '', length: '', width: '', height: '', stock: '0', images: '', isActive: true };

	onMount(async () => {
		try {
			const res = await fetch(`/api/products/${id}`);
			const data = await res.json();
			if (data.success && data.data) {
				const p = data.data;
				form = {
					nameSv: p.translations?.sv?.name || '', descriptionSv: p.translations?.sv?.description || '',
					nameEn: p.translations?.en?.name || '', descriptionEn: p.translations?.en?.description || '',
					price: String(p.price), sku: p.sku, category: p.category,
					weight: String(p.weight || ''), length: String(p.dimensions?.length || ''),
					width: String(p.dimensions?.width || ''), height: String(p.dimensions?.height || ''),
					stock: String(p.stock), images: (p.images || []).join('\n'), isActive: p.isActive,
				};
			} else { toast.error('Product not found'); goto('/admin/products'); }
		} catch { toast.error('Failed to load product'); goto('/admin/products'); } finally { loading = false; }
	});

	async function handleSave(e: Event) {
		e.preventDefault();
		saving = true;
		try {
			const body = {
				translations: { sv: { name: form.nameSv, description: form.descriptionSv }, en: { name: form.nameEn, description: form.descriptionEn } },
				price: parseFloat(form.price), sku: form.sku, category: form.category,
				weight: parseFloat(form.weight) || 0,
				dimensions: { length: parseFloat(form.length) || 0, width: parseFloat(form.width) || 0, height: parseFloat(form.height) || 0 },
				stock: parseInt(form.stock) || 0,
				images: form.images.split('\n').map(s => s.trim()).filter(Boolean),
				isActive: form.isActive,
			};
			const res = await fetch(`/api/products/${id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) });
			const data = await res.json();
			if (data.success) toast.success('Product updated');
			else toast.error(data.error || 'Failed to update');
		} catch { toast.error('Failed to update product'); } finally { saving = false; }
	}

	async function handleDelete() {
		deleteConfirm = false; deleting = true;
		try {
			const res = await fetch(`/api/products/${id}`, { method: 'DELETE' });
			if (res.ok) { toast.success('Product deleted'); goto('/admin/products'); }
			else toast.error('Failed to delete product');
		} catch { toast.error('Failed to delete product'); } finally { deleting = false; }
	}

	const inputClass = "w-full px-4 py-3 rounded-xl border-2 border-cream-300 dark:border-[#3f4946] bg-white dark:bg-[#2a3330] text-forest-800 dark:text-[#E8EDE8] focus:border-sage-600 focus:outline-none transition-colors";
	const labelClass = "block text-sm font-medium text-forest-700 dark:text-[#C5D4C5] mb-1";
</script>

<Toast />
{#if loading}
	<div class="flex items-center justify-center h-64"><div class="w-16 h-16 border-4 border-sage-600 border-t-transparent rounded-full animate-spin"></div></div>
{:else}
	<div class="space-y-6 max-w-3xl">
		<div class="flex items-center justify-between">
			<div class="flex items-center gap-4">
				<a href="/admin/products" class="p-2 rounded-lg hover:bg-cream-100 dark:hover:bg-[#2a3330] transition-colors">
					<ArrowLeft size={20} class="text-forest-700 dark:text-[#C5D4C5]" />
				</a>
				<h1 class="text-3xl font-serif font-bold text-forest-800 dark:text-[#E8EDE8]">Edit Product</h1>
			</div>
			<button on:click={() => deleteConfirm = true} disabled={deleting}
				class="flex items-center gap-2 px-4 py-2 rounded-xl bg-red-600 text-white hover:bg-red-700 transition-colors disabled:opacity-50">
				<Trash2 size={16} />Delete
			</button>
		</div>

		<form on:submit={handleSave} class="space-y-6">
			<div class="bg-white dark:bg-[#242a28] rounded-2xl shadow-soft p-6 border border-transparent dark:border-[#3f4946] space-y-4">
				<h2 class="text-lg font-semibold text-forest-800 dark:text-[#E8EDE8]">Swedish</h2>
				<div><label class={labelClass}>Name *</label><input type="text" bind:value={form.nameSv} required class={inputClass} /></div>
				<div><label class={labelClass}>Description</label><textarea bind:value={form.descriptionSv} rows={3} class={inputClass}></textarea></div>
			</div>

			<div class="bg-white dark:bg-[#242a28] rounded-2xl shadow-soft p-6 border border-transparent dark:border-[#3f4946] space-y-4">
				<h2 class="text-lg font-semibold text-forest-800 dark:text-[#E8EDE8]">English</h2>
				<div><label class={labelClass}>Name *</label><input type="text" bind:value={form.nameEn} required class={inputClass} /></div>
				<div><label class={labelClass}>Description</label><textarea bind:value={form.descriptionEn} rows={3} class={inputClass}></textarea></div>
			</div>

			<div class="bg-white dark:bg-[#242a28] rounded-2xl shadow-soft p-6 border border-transparent dark:border-[#3f4946] space-y-4">
				<h2 class="text-lg font-semibold text-forest-800 dark:text-[#E8EDE8]">Details</h2>
				<div class="grid grid-cols-2 gap-4">
					<div><label class={labelClass}>Price (SEK) *</label><input type="number" bind:value={form.price} required min="0" step="0.01" class={inputClass} /></div>
					<div><label class={labelClass}>SKU *</label><input type="text" bind:value={form.sku} required class={inputClass} /></div>
				</div>
				<div class="grid grid-cols-2 gap-4">
					<div><label class={labelClass}>Category *</label>
						<select bind:value={form.category} class={inputClass}>{#each CATEGORIES as c}<option value={c.value}>{c.label}</option>{/each}</select>
					</div>
					<div><label class={labelClass}>Stock</label><input type="number" bind:value={form.stock} min="0" class={inputClass} /></div>
				</div>
				<div><label class={labelClass}>Weight (g)</label><input type="number" bind:value={form.weight} min="0" class={inputClass} /></div>
				<div class="grid grid-cols-3 gap-4">
					<div><label class={labelClass}>Length (cm)</label><input type="number" bind:value={form.length} min="0" class={inputClass} /></div>
					<div><label class={labelClass}>Width (cm)</label><input type="number" bind:value={form.width} min="0" class={inputClass} /></div>
					<div><label class={labelClass}>Height (cm)</label><input type="number" bind:value={form.height} min="0" class={inputClass} /></div>
				</div>
				<div><label class={labelClass}>Image URLs (one per line)</label><textarea bind:value={form.images} rows={3} placeholder="https://..." class={inputClass}></textarea></div>
				<label class="flex items-center gap-2 cursor-pointer">
					<input type="checkbox" bind:checked={form.isActive} class="w-4 h-4 rounded text-sage-600" />
					<span class="text-sm font-medium text-forest-700 dark:text-[#C5D4C5]">Active (visible to customers)</span>
				</label>
			</div>

			<div class="flex gap-4">
				<button type="submit" disabled={saving} class="flex-1 py-3 bg-sage-600 hover:bg-sage-700 text-white rounded-full font-medium disabled:opacity-50 transition-colors">
					{saving ? 'Saving...' : 'Save Changes'}
				</button>
				<a href="/admin/products" class="px-6 py-3 border-2 border-cream-300 dark:border-[#3f4946] text-forest-700 dark:text-[#C5D4C5] rounded-full hover:bg-cream-50 dark:hover:bg-[#2a3330] transition-colors">Cancel</a>
			</div>
		</form>
	</div>

	{#if deleteConfirm}
		<div class="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
			<div class="bg-white dark:bg-[#242a28] rounded-xl p-6 max-w-sm mx-4 shadow-xl">
				<h3 class="text-lg font-semibold text-forest-800 dark:text-[#E8EDE8] mb-2">Delete product?</h3>
				<p class="text-forest-600 dark:text-[#C5D4C5] text-sm mb-6">Are you sure you want to delete <span class="font-medium">{form.nameSv}</span>? This cannot be undone.</p>
				<div class="flex gap-3">
					<button on:click={handleDelete} class="flex-1 px-4 py-2 bg-red-600 text-white font-medium rounded-lg hover:bg-red-700">Delete</button>
					<button on:click={() => deleteConfirm = false} class="flex-1 px-4 py-2 border border-cream-300 dark:border-[#3f4946] text-forest-700 dark:text-[#C5D4C5] font-medium rounded-lg hover:bg-cream-50 dark:hover:bg-[#2a3330]">Cancel</button>
				</div>
			</div>
		</div>
	{/if}
{/if}

// src/app/admin/products/[id]/page.tsx
'use client';

import { useState, useEffect, useCallback, use } from 'react';
import { useRouter } from 'next/navigation';
import Link from '@/components/i18n/Link';
import { ArrowLeftIcon, TrashIcon } from '@heroicons/react/24/outline';
import toast from 'react-hot-toast';
import { Product } from '@/types';

const CATEGORIES = [
  { value: 'essential-oils', label: 'Essential Oils' },
  { value: 'carrier-oils', label: 'Carrier Oils' },
  { value: 'diffusers', label: 'Diffusers' },
  { value: 'accessories', label: 'Accessories' },
  { value: 'gift-sets', label: 'Gift Sets' },
  { value: 'bundles', label: 'Bundles' },
];

export default function EditProductPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params);
  const router = useRouter();
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [deleting, setDeleting] = useState(false);
  const [deleteConfirm, setDeleteConfirm] = useState(false);

  const [form, setForm] = useState({
    nameSv: '',
    descriptionSv: '',
    nameEn: '',
    descriptionEn: '',
    price: '',
    sku: '',
    category: 'essential-oils',
    weight: '',
    length: '',
    width: '',
    height: '',
    stock: '0',
    images: '',
    isActive: true,
  });

  const fetchProduct = useCallback(async () => {
    try {
      const res = await fetch(`/api/products/${id}`);
      const data = await res.json();
      if (data.success && data.data) {
        const p: Product = data.data;
        setForm({
          nameSv: p.translations.sv.name,
          descriptionSv: p.translations.sv.description,
          nameEn: p.translations.en.name,
          descriptionEn: p.translations.en.description,
          price: String(p.price),
          sku: p.sku,
          category: p.category,
          weight: String(p.weight),
          length: String(p.dimensions.length),
          width: String(p.dimensions.width),
          height: String(p.dimensions.height),
          stock: String(p.stock),
          images: (p.images || []).join('\n'),
          isActive: p.isActive,
        });
      } else {
        toast.error('Product not found');
        router.push('/admin/products');
      }
    } catch {
      toast.error('Failed to load product');
      router.push('/admin/products');
    } finally {
      setLoading(false);
    }
  }, [id, router]);

  useEffect(() => {
    fetchProduct();
  }, [fetchProduct]);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    const { name, value, type } = e.target;
    setForm(prev => ({
      ...prev,
      [name]: type === 'checkbox' ? (e.target as HTMLInputElement).checked : value,
    }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSaving(true);

    const imageList = form.images
      .split('\n')
      .map(url => url.trim())
      .filter(Boolean);

    const body = {
      name: form.nameEn || form.nameSv,
      description: form.descriptionEn || form.descriptionSv,
      price: parseFloat(form.price),
      category: form.category,
      images: imageList,
      stock: parseInt(form.stock),
      sku: form.sku,
      weight: parseFloat(form.weight) || 0,
      dimensions: {
        length: parseFloat(form.length) || 0,
        width: parseFloat(form.width) || 0,
        height: parseFloat(form.height) || 0,
      },
      isActive: form.isActive,
      translations: {
        sv: { name: form.nameSv, description: form.descriptionSv },
        en: { name: form.nameEn, description: form.descriptionEn },
      },
    };

    try {
      const res = await fetch(`/api/products/${id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
      });
      const data = await res.json();

      if (data.success) {
        toast.success('Product updated successfully');
      } else {
        toast.error(data.error || 'Failed to update product');
      }
    } catch {
      toast.error('Failed to update product');
    } finally {
      setSaving(false);
    }
  };

  const handleDelete = async () => {
    setDeleteConfirm(false);
    setDeleting(true);

    try {
      const res = await fetch(`/api/products/${id}`, { method: 'DELETE' });
      const data = await res.json();

      if (data.success) {
        toast.success('Product deleted');
        router.push('/admin/products');
      } else {
        toast.error(data.error || 'Failed to delete product');
      }
    } catch {
      toast.error('Failed to delete product');
    } finally {
      setDeleting(false);
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-96">
        <div className="w-16 h-16 border-4 border-sage-600 border-t-transparent rounded-full animate-spin" />
      </div>
    );
  }

  return (
    <div className="max-w-3xl mx-auto space-y-6">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-4">
          <Link
            href="/admin/products"
            className="p-2 rounded-lg hover:bg-cream-100 dark:hover:bg-[#2a3330] transition-colors text-forest-600 dark:text-[#C5D4C5]"
          >
            <ArrowLeftIcon className="h-5 w-5" />
          </Link>
          <div>
            <h1 className="text-3xl font-serif font-bold text-forest-800 dark:text-[#E8EDE8]">Edit Product</h1>
            <p className="text-forest-600 dark:text-[#C5D4C5] mt-1">Update product details</p>
          </div>
        </div>
        <button
          onClick={() => setDeleteConfirm(true)}
          disabled={deleting}
          className="inline-flex items-center gap-2 px-4 py-2 rounded-full border-2 border-red-200 dark:border-red-800 text-red-600 dark:text-red-400 font-medium hover:bg-red-50 dark:hover:bg-red-900/20 transition-all disabled:opacity-50"
        >
          <TrashIcon className="h-4 w-4" />
          {deleting ? 'Deleting...' : 'Delete'}
        </button>
      </div>

      <form onSubmit={handleSubmit} className="space-y-6">
        {/* Swedish */}
        <div className="bg-white dark:bg-[#242a28] rounded-2xl shadow-soft p-6 space-y-4">
          <h2 className="text-lg font-semibold text-forest-800 dark:text-[#E8EDE8]">Swedish (Svenska)</h2>
          <div>
            <label htmlFor="nameSv" className="block text-sm font-medium text-forest-700 dark:text-[#C5D4C5] mb-1">Name (SV) *</label>
            <input
              id="nameSv"
              name="nameSv"
              value={form.nameSv}
              onChange={handleChange}
              required
              className="w-full px-4 py-3 rounded-xl border-2 border-cream-300 dark:border-[#3f4946] bg-white dark:bg-[#2a3330] text-forest-800 dark:text-[#E8EDE8] focus:border-sage-600 focus:outline-none"
            />
          </div>
          <div>
            <label htmlFor="descriptionSv" className="block text-sm font-medium text-forest-700 dark:text-[#C5D4C5] mb-1">Description (SV) *</label>
            <textarea
              id="descriptionSv"
              name="descriptionSv"
              value={form.descriptionSv}
              onChange={handleChange}
              required
              rows={3}
              className="w-full px-4 py-3 rounded-xl border-2 border-cream-300 dark:border-[#3f4946] bg-white dark:bg-[#2a3330] text-forest-800 dark:text-[#E8EDE8] focus:border-sage-600 focus:outline-none resize-none"
            />
          </div>
        </div>

        {/* English */}
        <div className="bg-white dark:bg-[#242a28] rounded-2xl shadow-soft p-6 space-y-4">
          <h2 className="text-lg font-semibold text-forest-800 dark:text-[#E8EDE8]">English</h2>
          <div>
            <label htmlFor="nameEn" className="block text-sm font-medium text-forest-700 dark:text-[#C5D4C5] mb-1">Name (EN) *</label>
            <input
              id="nameEn"
              name="nameEn"
              value={form.nameEn}
              onChange={handleChange}
              required
              className="w-full px-4 py-3 rounded-xl border-2 border-cream-300 dark:border-[#3f4946] bg-white dark:bg-[#2a3330] text-forest-800 dark:text-[#E8EDE8] focus:border-sage-600 focus:outline-none"
            />
          </div>
          <div>
            <label htmlFor="descriptionEn" className="block text-sm font-medium text-forest-700 dark:text-[#C5D4C5] mb-1">Description (EN) *</label>
            <textarea
              id="descriptionEn"
              name="descriptionEn"
              value={form.descriptionEn}
              onChange={handleChange}
              required
              rows={3}
              className="w-full px-4 py-3 rounded-xl border-2 border-cream-300 dark:border-[#3f4946] bg-white dark:bg-[#2a3330] text-forest-800 dark:text-[#E8EDE8] focus:border-sage-600 focus:outline-none resize-none"
            />
          </div>
        </div>

        {/* Pricing & Catalog */}
        <div className="bg-white dark:bg-[#242a28] rounded-2xl shadow-soft p-6 space-y-4">
          <h2 className="text-lg font-semibold text-forest-800 dark:text-[#E8EDE8]">Pricing & Catalog</h2>
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label htmlFor="price" className="block text-sm font-medium text-forest-700 dark:text-[#C5D4C5] mb-1">Price (kr) *</label>
              <input
                id="price"
                name="price"
                type="number"
                min="0"
                step="0.01"
                value={form.price}
                onChange={handleChange}
                required
                className="w-full px-4 py-3 rounded-xl border-2 border-cream-300 dark:border-[#3f4946] bg-white dark:bg-[#2a3330] text-forest-800 dark:text-[#E8EDE8] focus:border-sage-600 focus:outline-none"
              />
            </div>
            <div>
              <label htmlFor="sku" className="block text-sm font-medium text-forest-700 dark:text-[#C5D4C5] mb-1">SKU *</label>
              <input
                id="sku"
                name="sku"
                value={form.sku}
                onChange={handleChange}
                required
                className="w-full px-4 py-3 rounded-xl border-2 border-cream-300 dark:border-[#3f4946] bg-white dark:bg-[#2a3330] text-forest-800 dark:text-[#E8EDE8] focus:border-sage-600 focus:outline-none"
              />
            </div>
          </div>
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label htmlFor="category" className="block text-sm font-medium text-forest-700 dark:text-[#C5D4C5] mb-1">Category *</label>
              <select
                id="category"
                name="category"
                value={form.category}
                onChange={handleChange}
                className="w-full px-4 py-3 rounded-xl border-2 border-cream-300 dark:border-[#3f4946] bg-white dark:bg-[#2a3330] text-forest-800 dark:text-[#E8EDE8] focus:border-sage-600 focus:outline-none"
              >
                {CATEGORIES.map(c => (
                  <option key={c.value} value={c.value}>{c.label}</option>
                ))}
              </select>
            </div>
            <div>
              <label htmlFor="stock" className="block text-sm font-medium text-forest-700 dark:text-[#C5D4C5] mb-1">Stock</label>
              <input
                id="stock"
                name="stock"
                type="number"
                min="0"
                value={form.stock}
                onChange={handleChange}
                className="w-full px-4 py-3 rounded-xl border-2 border-cream-300 dark:border-[#3f4946] bg-white dark:bg-[#2a3330] text-forest-800 dark:text-[#E8EDE8] focus:border-sage-600 focus:outline-none"
              />
            </div>
          </div>
        </div>

        {/* Physical */}
        <div className="bg-white dark:bg-[#242a28] rounded-2xl shadow-soft p-6 space-y-4">
          <h2 className="text-lg font-semibold text-forest-800 dark:text-[#E8EDE8]">Physical Details</h2>
          <div>
            <label htmlFor="weight" className="block text-sm font-medium text-forest-700 dark:text-[#C5D4C5] mb-1">Weight (g)</label>
            <input
              id="weight"
              name="weight"
              type="number"
              min="0"
              value={form.weight}
              onChange={handleChange}
              className="w-full px-4 py-3 rounded-xl border-2 border-cream-300 dark:border-[#3f4946] bg-white dark:bg-[#2a3330] text-forest-800 dark:text-[#E8EDE8] focus:border-sage-600 focus:outline-none"
            />
          </div>
          <div className="grid grid-cols-3 gap-4">
            <div>
              <label htmlFor="length" className="block text-sm font-medium text-forest-700 dark:text-[#C5D4C5] mb-1">Length (cm)</label>
              <input
                id="length"
                name="length"
                type="number"
                min="0"
                step="0.1"
                value={form.length}
                onChange={handleChange}
                className="w-full px-4 py-3 rounded-xl border-2 border-cream-300 dark:border-[#3f4946] bg-white dark:bg-[#2a3330] text-forest-800 dark:text-[#E8EDE8] focus:border-sage-600 focus:outline-none"
              />
            </div>
            <div>
              <label htmlFor="width" className="block text-sm font-medium text-forest-700 dark:text-[#C5D4C5] mb-1">Width (cm)</label>
              <input
                id="width"
                name="width"
                type="number"
                min="0"
                step="0.1"
                value={form.width}
                onChange={handleChange}
                className="w-full px-4 py-3 rounded-xl border-2 border-cream-300 dark:border-[#3f4946] bg-white dark:bg-[#2a3330] text-forest-800 dark:text-[#E8EDE8] focus:border-sage-600 focus:outline-none"
              />
            </div>
            <div>
              <label htmlFor="height" className="block text-sm font-medium text-forest-700 dark:text-[#C5D4C5] mb-1">Height (cm)</label>
              <input
                id="height"
                name="height"
                type="number"
                min="0"
                step="0.1"
                value={form.height}
                onChange={handleChange}
                className="w-full px-4 py-3 rounded-xl border-2 border-cream-300 dark:border-[#3f4946] bg-white dark:bg-[#2a3330] text-forest-800 dark:text-[#E8EDE8] focus:border-sage-600 focus:outline-none"
              />
            </div>
          </div>
        </div>

        {/* Images & Status */}
        <div className="bg-white dark:bg-[#242a28] rounded-2xl shadow-soft p-6 space-y-4">
          <h2 className="text-lg font-semibold text-forest-800 dark:text-[#E8EDE8]">Images & Status</h2>
          <div>
            <label htmlFor="images" className="block text-sm font-medium text-forest-700 dark:text-[#C5D4C5] mb-1">
              Image URLs (one per line)
            </label>
            <textarea
              id="images"
              name="images"
              value={form.images}
              onChange={handleChange}
              rows={3}
              className="w-full px-4 py-3 rounded-xl border-2 border-cream-300 dark:border-[#3f4946] bg-white dark:bg-[#2a3330] text-forest-800 dark:text-[#E8EDE8] focus:border-sage-600 focus:outline-none resize-none font-mono text-sm"
            />
          </div>
          <div className="flex items-center gap-3">
            <input
              type="checkbox"
              id="isActive"
              name="isActive"
              checked={form.isActive}
              onChange={handleChange}
              className="w-5 h-5 rounded border-cream-300 text-sage-600 focus:ring-sage-500"
            />
            <label htmlFor="isActive" className="text-sm font-medium text-forest-700 dark:text-[#C5D4C5]">
              Active (visible in store)
            </label>
          </div>
        </div>

        {/* Actions */}
        <div className="flex items-center justify-end gap-4">
          <Link
            href="/admin/products"
            className="px-6 py-3 rounded-full border-2 border-cream-300 dark:border-[#3f4946] text-forest-700 dark:text-[#C5D4C5] font-semibold hover:bg-cream-100 dark:hover:bg-[#2a3330] transition-all"
          >
            Cancel
          </Link>
          <button
            type="submit"
            disabled={saving}
            className="px-8 py-3 rounded-full bg-sage-600 text-white font-semibold hover:bg-sage-700 transition-all shadow-lg hover:shadow-xl disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {saving ? 'Saving...' : 'Save Changes'}
          </button>
        </div>
      </form>

      {/* Delete Confirmation Modal */}
      {deleteConfirm && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white dark:bg-[#242a28] rounded-xl p-6 max-w-sm mx-4 shadow-xl">
            <h3 className="text-lg font-semibold text-forest-800 dark:text-[#E8EDE8] mb-2">Delete product?</h3>
            <p className="text-forest-600 dark:text-[#C5D4C5] text-sm mb-6">
              Are you sure you want to delete this product? It will be hidden from the store.
            </p>
            <div className="flex gap-3">
              <button
                onClick={handleDelete}
                className="flex-1 px-4 py-2 bg-red-600 text-white font-medium rounded-lg hover:bg-red-700 transition-colors"
              >
                Delete
              </button>
              <button
                onClick={() => setDeleteConfirm(false)}
                className="flex-1 px-4 py-2 border border-cream-300 dark:border-[#3f4946] text-forest-700 dark:text-[#C5D4C5] font-medium rounded-lg hover:bg-cream-50 dark:hover:bg-[#2a3330] transition-colors"
              >
                Cancel
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
