// sveltekit/src/lib/components/products/ProductFilters.svelte
<script lang="ts">
	export let locale: 'sv' | 'en' = 'sv';
	export let filters: Record<string, unknown> = {};
	export let options: { categories: { category: string; count: number; displayName: { sv: string; en: string } }[]; priceRange: { min: number; max: number } } = { categories: [], priceRange: { min: 0, max: 1000 } };
	export let onFiltersChange: (f: Record<string, unknown>) => void = () => {};
	export let className = '';

	function setCategory(cat: string) {
		onFiltersChange({ ...filters, category: cat || undefined });
	}

	function clearFilters() {
		onFiltersChange({});
	}
</script>

<aside class="bg-white dark:bg-[#2a3330] rounded-2xl p-5 space-y-6 {className}">
	<div class="flex items-center justify-between">
		<h3 class="font-semibold text-forest-800 dark:text-[#E8EDE8]">{locale === 'sv' ? 'Filter' : 'Filters'}</h3>
		{#if Object.keys(filters).length > 0}
			<button on:click={clearFilters} class="text-sm text-sage-600 hover:text-sage-700">
				{locale === 'sv' ? 'Rensa' : 'Clear'}
			</button>
		{/if}
	</div>

	<!-- Categories -->
	<div>
		<h4 class="text-sm font-medium text-forest-700 dark:text-[#C5D4C5] mb-3">{locale === 'sv' ? 'Kategori' : 'Category'}</h4>
		<div class="space-y-2">
			<button
				on:click={() => setCategory('')}
				class="block w-full text-left px-3 py-2 rounded-lg text-sm transition-colors {!filters.category ? 'bg-sage-100 dark:bg-sage-900/30 text-sage-700 dark:text-sage-300 font-medium' : 'text-forest-700 dark:text-[#C5D4C5] hover:bg-cream-100 dark:hover:bg-[#343c39]'}"
			>
				{locale === 'sv' ? 'Alla kategorier' : 'All categories'}
			</button>
			{#each options.categories as cat}
				<button
					on:click={() => setCategory(cat.category)}
					class="flex items-center justify-between w-full px-3 py-2 rounded-lg text-sm transition-colors {filters.category === cat.category ? 'bg-sage-100 dark:bg-sage-900/30 text-sage-700 dark:text-sage-300 font-medium' : 'text-forest-700 dark:text-[#C5D4C5] hover:bg-cream-100 dark:hover:bg-[#343c39]'}"
				>
					<span>{cat.displayName[locale]}</span>
					<span class="text-forest-500 dark:text-[#8A9A8A] text-xs">({cat.count})</span>
				</button>
			{/each}
		</div>
	</div>

	<!-- In Stock -->
	<div>
		<label class="flex items-center gap-3 cursor-pointer">
			<input
				type="checkbox"
				checked={!!filters.inStock}
				on:change={e => onFiltersChange({ ...filters, inStock: (e.target as HTMLInputElement).checked || undefined })}
				class="h-4 w-4 text-sage-600 rounded border-cream-300 dark:border-[#4a5552]"
			/>
			<span class="text-sm text-forest-700 dark:text-[#C5D4C5]">{locale === 'sv' ? 'Bara i lager' : 'In stock only'}</span>
		</label>
	</div>
</aside>

// src/components/products/ProductFilters.tsx
'use client';

import { useState, useEffect } from 'react';
import { ChevronDownIcon, FunnelIcon } from '@heroicons/react/24/outline';
import { Disclosure } from '@headlessui/react';

interface FilterOptions {
  categories: { category: string; count: number; displayName: { sv: string; en: string } }[];
  priceRange: { min: number; max: number };
}

interface ActiveFilters {
  category?: string;
  minPrice?: number;
  maxPrice?: number;
  inStock?: boolean;
  sortBy?: 'name' | 'price' | 'created';
  sortOrder?: 'asc' | 'desc';
}

interface ProductFiltersProps {
  locale?: 'sv' | 'en';
  filters: ActiveFilters;
  options: FilterOptions;
  onFiltersChange: (filters: ActiveFilters) => void;
  className?: string;
}

export const ProductFilters = ({
  locale = 'sv',
  filters,
  options,
  onFiltersChange,
  className = ''
}: ProductFiltersProps) => {
  const [localFilters, setLocalFilters] = useState<ActiveFilters>(filters);
  const [isOpen, setIsOpen] = useState(false);

  useEffect(() => {
    setLocalFilters(filters);
  }, [filters]);

  const handleFilterChange = (key: keyof ActiveFilters, value: any) => {
    const newFilters = { ...localFilters, [key]: value };
    setLocalFilters(newFilters);
    onFiltersChange(newFilters);
  };

  const clearFilters = () => {
    const clearedFilters: ActiveFilters = {};
    setLocalFilters(clearedFilters);
    onFiltersChange(clearedFilters);
  };

  const hasActiveFilters = Object.keys(localFilters).length > 0;

  const sortOptions = [
    { value: 'name-asc', label: locale === 'sv' ? 'Namn A-Ö' : 'Name A-Z', sortBy: 'name', sortOrder: 'asc' },
    { value: 'name-desc', label: locale === 'sv' ? 'Namn Ö-A' : 'Name Z-A', sortBy: 'name', sortOrder: 'desc' },
    { value: 'price-asc', label: locale === 'sv' ? 'Pris låg-hög' : 'Price low-high', sortBy: 'price', sortOrder: 'asc' },
    { value: 'price-desc', label: locale === 'sv' ? 'Pris hög-låg' : 'Price high-low', sortBy: 'price', sortOrder: 'desc' },
    { value: 'created-desc', label: locale === 'sv' ? 'Senast tillagda' : 'Newest first', sortBy: 'created', sortOrder: 'desc' },
  ];

  const getCurrentSortValue = () => {
    const sortBy = localFilters.sortBy || 'name';
    const sortOrder = localFilters.sortOrder || 'asc';
    return `${sortBy}-${sortOrder}`;
  };

  const handleSortChange = (value: string) => {
    const [sortBy, sortOrder] = value.split('-') as ['name' | 'price' | 'created', 'asc' | 'desc'];
    handleFilterChange('sortBy', sortBy);
    handleFilterChange('sortOrder', sortOrder);
  };

  return (
    <div className={`bg-white dark:bg-[#242a28] rounded-lg shadow-sm border border-cream-200 dark:border-[#3f4946] ${className}`}>
      {/* Mobile Filter Toggle */}
      <div className="lg:hidden">
        <button
          onClick={() => setIsOpen(!isOpen)}
          className="w-full px-4 py-3 flex items-center justify-between text-sm font-medium text-forest-700 dark:text-[#C5D4C5]"
        >
          <div className="flex items-center">
            <FunnelIcon className="h-5 w-5 mr-2" />
            {locale === 'sv' ? 'Filter & Sortering' : 'Filters & Sorting'}
            {hasActiveFilters && (
              <span className="ml-2 bg-sage-100 dark:bg-[#2a3330] text-sage-800 dark:text-sage-300 text-xs px-2 py-1 rounded-full">
                {Object.keys(localFilters).length}
              </span>
            )}
          </div>
          <ChevronDownIcon className={`h-5 w-5 transform transition-transform ${isOpen ? 'rotate-180' : ''}`} />
        </button>
      </div>

      {/* Filter Content */}
      <div className={`${isOpen ? 'block' : 'hidden'} lg:block p-4 space-y-6`}>
        {/* Sort Options */}
        <div>
          <label className="block text-sm font-medium text-forest-700 dark:text-[#C5D4C5] mb-2">
            {locale === 'sv' ? 'Sortera efter' : 'Sort by'}
          </label>
          <select
            value={getCurrentSortValue()}
            onChange={(e) => handleSortChange(e.target.value)}
            className="block w-full px-3 py-2 border border-cream-300 dark:border-[#4a5552] rounded-md shadow-sm bg-white dark:bg-[#2a3330] dark:text-[#E8EDE8] focus:outline-none focus:ring-sage-500 focus:border-sage-500"
          >
            {sortOptions.map((option) => (
              <option key={option.value} value={option.value}>
                {option.label}
              </option>
            ))}
          </select>
        </div>

        {/* Categories */}
        <Disclosure defaultOpen>
          {({ open }) => (
            <div>
              <Disclosure.Button className="flex w-full justify-between rounded-lg bg-cream-50 dark:bg-[#2a3330] px-4 py-2 text-left text-sm font-medium text-forest-900 dark:text-[#E8EDE8] hover:bg-cream-100 dark:hover:bg-[#343c39] focus:outline-none focus-visible:ring focus-visible:ring-sage-500 focus-visible:ring-opacity-75">
                <span>{locale === 'sv' ? 'Kategorier' : 'Categories'}</span>
                <ChevronDownIcon className={`${open ? 'rotate-180 transform' : ''} h-5 w-5 text-forest-500 dark:text-[#8A9A8A]`} />
              </Disclosure.Button>
              <Disclosure.Panel className="pt-4 pb-2 text-sm">
                <div className="space-y-2">
                  <label className="flex items-center">
                    <input
                      type="radio"
                      name="category"
                      checked={!localFilters.category}
                      onChange={() => handleFilterChange('category', undefined)}
                      className="h-4 w-4 text-sage-600 focus:ring-sage-500 border-cream-300 dark:border-[#4a5552]"
                    />
                    <span className="ml-2 text-forest-700 dark:text-[#C5D4C5]">
                      {locale === 'sv' ? 'Alla kategorier' : 'All categories'}
                    </span>
                  </label>
                  {options.categories.map((category) => (
                    <label key={category.category} className="flex items-center">
                      <input
                        type="radio"
                        name="category"
                        value={category.category}
                        checked={localFilters.category === category.category}
                        onChange={(e) => handleFilterChange('category', e.target.value)}
                        className="h-4 w-4 text-sage-600 focus:ring-sage-500 border-cream-300 dark:border-[#4a5552]"
                      />
                      <span className="ml-2 text-forest-700 dark:text-[#C5D4C5]">
                        {category.displayName[locale]} ({category.count})
                      </span>
                    </label>
                  ))}
                </div>
              </Disclosure.Panel>
            </div>
          )}
        </Disclosure>

        {/* Price Range */}
        <Disclosure defaultOpen>
          {({ open }) => (
            <div>
              <Disclosure.Button className="flex w-full justify-between rounded-lg bg-cream-50 dark:bg-[#2a3330] px-4 py-2 text-left text-sm font-medium text-forest-900 dark:text-[#E8EDE8] hover:bg-cream-100 dark:hover:bg-[#343c39] focus:outline-none focus-visible:ring focus-visible:ring-sage-500 focus-visible:ring-opacity-75">
                <span>{locale === 'sv' ? 'Pris' : 'Price'}</span>
                <ChevronDownIcon className={`${open ? 'rotate-180 transform' : ''} h-5 w-5 text-forest-500 dark:text-[#8A9A8A]`} />
              </Disclosure.Button>
              <Disclosure.Panel className="pt-4 pb-2 text-sm">
                <div className="space-y-4">
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <label className="block text-xs font-medium text-forest-700 dark:text-[#C5D4C5] mb-1">
                        {locale === 'sv' ? 'Min' : 'Min'}
                      </label>
                      <input
                        type="number"
                        min={options.priceRange.min}
                        max={options.priceRange.max}
                        value={localFilters.minPrice || ''}
                        onChange={(e) => handleFilterChange('minPrice', e.target.value ? Number(e.target.value) : undefined)}
                        className="block w-full px-3 py-2 border border-cream-300 dark:border-[#4a5552] rounded-md shadow-sm bg-white dark:bg-[#2a3330] dark:text-[#E8EDE8] focus:outline-none focus:ring-sage-500 focus:border-sage-500 text-sm"
                        placeholder={`${options.priceRange.min}`}
                      />
                    </div>
                    <div>
                      <label className="block text-xs font-medium text-forest-700 dark:text-[#C5D4C5] mb-1">
                        {locale === 'sv' ? 'Max' : 'Max'}
                      </label>
                      <input
                        type="number"
                        min={options.priceRange.min}
                        max={options.priceRange.max}
                        value={localFilters.maxPrice || ''}
                        onChange={(e) => handleFilterChange('maxPrice', e.target.value ? Number(e.target.value) : undefined)}
                        className="block w-full px-3 py-2 border border-cream-300 dark:border-[#4a5552] rounded-md shadow-sm bg-white dark:bg-[#2a3330] dark:text-[#E8EDE8] focus:outline-none focus:ring-sage-500 focus:border-sage-500 text-sm"
                        placeholder={`${options.priceRange.max}`}
                      />
                    </div>
                  </div>
                </div>
              </Disclosure.Panel>
            </div>
          )}
        </Disclosure>

        {/* Availability */}
        <div>
          <label className="flex items-center">
            <input
              type="checkbox"
              checked={localFilters.inStock || false}
              onChange={(e) => handleFilterChange('inStock', e.target.checked ? true : undefined)}
              className="h-4 w-4 text-sage-600 focus:ring-sage-500 border-cream-300 dark:border-[#4a5552] rounded"
            />
            <span className="ml-2 text-sm text-forest-700 dark:text-[#C5D4C5]">
              {locale === 'sv' ? 'Endast i lager' : 'In stock only'}
            </span>
          </label>
        </div>

        {/* Clear Filters */}
        {hasActiveFilters && (
          <button
            onClick={clearFilters}
            className="w-full px-4 py-2 text-sm font-medium text-sage-700 dark:text-sage-400 hover:text-sage-800 border border-sage-200 dark:border-[#3f4946] hover:border-sage-300 rounded-md transition-colors"
          >
            {locale === 'sv' ? 'Rensa alla filter' : 'Clear all filters'}
          </button>
        )}
      </div>
    </div>
  );
};
