// sveltekit/src/routes/contact/+page.svelte
<script lang="ts">
	import { locale } from '$lib/stores/locale';
	import { toast } from '$lib/stores/toast';
	import Toast from '$lib/components/ui/Toast.svelte';

	let form = { name: '', email: '', subject: '', message: '' };
	let submitting = false;
	let submitted = false;

	async function handleSubmit() {
		submitting = true;
		try {
			const res = await fetch('/api/contact', {
				method: 'POST',
				headers: { 'Content-Type': 'application/json' },
				body: JSON.stringify(form),
			});
			const data = await res.json();
			if (data.success) {
				submitted = true;
				toast.success($locale === 'sv' ? 'Meddelande skickat!' : 'Message sent!');
				form = { name: '', email: '', subject: '', message: '' };
			} else {
				toast.error(data.error ?? ($locale === 'sv' ? 'Något gick fel' : 'Something went wrong'));
			}
		} catch {
			toast.error($locale === 'sv' ? 'Kunde inte skicka meddelandet' : 'Failed to send message');
		} finally {
			submitting = false;
		}
	}
</script>

<svelte:head><title>{$locale === 'sv' ? 'Kontakt' : 'Contact'} – Fortune Essence</title></svelte:head>
<Toast />

<div class="min-h-screen bg-cream-50 dark:bg-[#1a1f1e] py-16">
	<div class="container mx-auto px-4 max-w-2xl">
		<div class="text-center mb-12">
			<h1 class="text-4xl font-serif font-bold text-forest-800 dark:text-[#E8EDE8] mb-4">
				{$locale === 'sv' ? 'Kontakta oss' : 'Contact us'}
			</h1>
			<p class="text-forest-600 dark:text-[#B8C5B8]">
				{$locale === 'sv' ? 'Vi svarar inom 1–2 arbetsdagar' : 'We respond within 1–2 business days'}
			</p>
		</div>

		{#if submitted}
			<div class="bg-sage-50 dark:bg-sage-900/20 border border-sage-200 dark:border-sage-800 rounded-2xl p-8 text-center">
				<div class="text-4xl mb-4">✅</div>
				<h2 class="text-xl font-semibold text-forest-800 dark:text-[#E8EDE8] mb-2">{$locale === 'sv' ? 'Tack för ditt meddelande!' : 'Thank you for your message!'}</h2>
				<p class="text-forest-600 dark:text-[#B8C5B8]">{$locale === 'sv' ? 'Vi återkommer så snart som möjligt.' : 'We will get back to you as soon as possible.'}</p>
				<button on:click={() => submitted = false} class="mt-4 px-6 py-2 bg-sage-600 text-white rounded-full hover:bg-sage-700 transition-colors">
					{$locale === 'sv' ? 'Skicka nytt meddelande' : 'Send another message'}
				</button>
			</div>
		{:else}
			<form on:submit|preventDefault={handleSubmit} class="bg-white dark:bg-[#2a3330] rounded-2xl p-8 shadow-soft space-y-5">
				{#each [['name', $locale === 'sv' ? 'Namn' : 'Name', 'text'], ['email', $locale === 'sv' ? 'E-post' : 'Email', 'email'], ['subject', $locale === 'sv' ? 'Ämne' : 'Subject', 'text']] as [field, label, type]}
					<div>
						<label class="block text-sm font-medium text-forest-700 dark:text-[#C5D4C5] mb-1">{label}</label>
						<input type={type} bind:value={form[field]} required class="w-full px-4 py-3 border border-cream-300 dark:border-[#4a5552] rounded-xl bg-white dark:bg-[#343c39] dark:text-[#E8EDE8] focus:outline-none focus:ring-2 focus:ring-sage-500" />
					</div>
				{/each}
				<div>
					<label class="block text-sm font-medium text-forest-700 dark:text-[#C5D4C5] mb-1">{$locale === 'sv' ? 'Meddelande' : 'Message'}</label>
					<textarea bind:value={form.message} rows={5} required class="w-full px-4 py-3 border border-cream-300 dark:border-[#4a5552] rounded-xl bg-white dark:bg-[#343c39] dark:text-[#E8EDE8] focus:outline-none focus:ring-2 focus:ring-sage-500 resize-none"></textarea>
				</div>
				<button type="submit" disabled={submitting} class="w-full py-3 bg-sage-600 hover:bg-sage-700 text-white rounded-full font-medium transition-colors disabled:opacity-50">
					{submitting ? ($locale === 'sv' ? 'Skickar...' : 'Sending...') : ($locale === 'sv' ? 'Skicka meddelande' : 'Send message')}
				</button>
			</form>
		{/if}

		<div class="mt-8 grid grid-cols-1 sm:grid-cols-2 gap-4 text-center text-sm text-forest-600 dark:text-[#B8C5B8]">
			<div class="bg-white dark:bg-[#2a3330] rounded-xl p-4 shadow-soft">
				<p class="font-medium text-forest-800 dark:text-[#E8EDE8]">📧 {$locale === 'sv' ? 'E-post' : 'Email'}</p>
				<p>info@fortuneessence.se</p>
			</div>
			<div class="bg-white dark:bg-[#2a3330] rounded-xl p-4 shadow-soft">
				<p class="font-medium text-forest-800 dark:text-[#E8EDE8]">⏰ {$locale === 'sv' ? 'Svarstid' : 'Response time'}</p>
				<p>{$locale === 'sv' ? '1–2 arbetsdagar' : '1–2 business days'}</p>
			</div>
		</div>
	</div>
</div>

// src/app/contact/page.tsx
'use client';

import { useState } from 'react';
import { useLocale } from '@/contexts/LocaleContext';
import Link from 'next/link';
import {
  MapPinIcon,
  PhoneIcon,
  EnvelopeIcon,
  ClockIcon,
  ChatBubbleLeftIcon,
  QuestionMarkCircleIcon
} from '@heroicons/react/24/outline';

export default function ContactPage() {
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    subject: '',
    message: ''
  });
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitted, setSubmitted] = useState(false);

  const { locale } = useLocale();

  const [error, setError] = useState<string | null>(null);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);
    setError(null);

    try {
      const res = await fetch('/api/contact', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(formData),
      });

      const data = await res.json();

      if (!res.ok || !data.success) {
        setError(locale === 'sv' ? 'Något gick fel. Försök igen.' : 'Something went wrong. Please try again.');
        return;
      }

      setSubmitted(true);
      setFormData({ name: '', email: '', subject: '', message: '' });
    } catch {
      setError(locale === 'sv' ? 'Kunde inte skicka meddelandet. Försök igen.' : 'Failed to send message. Please try again.');
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value
    });
  };

  const contactInfo = [
    {
      icon: MapPinIcon,
      title: locale === 'sv' ? 'Plats' : 'Location',
      content: locale === 'sv'
        ? 'Göteborg, Sverige\n(Endast online)'
        : 'Gothenburg, Sweden\n(Online only)',
    },
    // Phone section commented out - no company phone yet
    // {
    //   icon: PhoneIcon,
    //   title: locale === 'sv' ? 'Telefon' : 'Phone',
    //   content: '+46 31 123 456 78',
    // },
    {
      icon: EnvelopeIcon,
      title: locale === 'sv' ? 'E-post' : 'Email',
      content: 'info@fortune-essence.se',
    },
    {
      icon: ClockIcon,
      title: locale === 'sv' ? 'Kundservice' : 'Customer Service',
      content: locale === 'sv'
        ? 'Mån-Fre: 9:00-17:00\nSvarar på e-post inom 24h'
        : 'Mon-Fri: 9:00-17:00\nEmail replies within 24h',
    },
  ];

  return (
    <div className="min-h-screen">
      {/* Hero Section */}
      <section className="relative overflow-hidden bg-gradient-to-br from-yellow-100 via-purple-50 to-yellow-50 dark:from-[#2a3330] dark:via-[#1a1f1e] dark:to-[#242a28] py-20">
        <div className="absolute inset-0 bg-[url('/images/patterns/oil-drops.svg')] opacity-10"></div>
        <div className="container mx-auto px-4 relative">
          <div className="text-center max-w-4xl mx-auto">
            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold text-forest-900 dark:text-[#E8EDE8] mb-6">
              <span className="block">
                {locale === 'sv' ? 'Kontakta Oss' : 'Contact Us'}
              </span>
              <span className="block bg-gradient-to-r from-yellow-600 via-purple-600 to-yellow-600 dark:from-sage-400 dark:via-sage-300 dark:to-sage-400 bg-clip-text text-transparent">
                {locale === 'sv' ? 'Vi Hjälper Gärna' : 'We\'re Here to Help'}
              </span>
            </h1>
            <p className="text-xl text-forest-700 dark:text-[#B8C5B8] mb-8">
              {locale === 'sv' 
                ? 'Har du frågor om våra produkter eller behöver hjälp med din beställning? Tveka inte att höra av dig!'
                : 'Do you have questions about our products or need help with your order? Don\'t hesitate to get in touch!'
              }
            </p>
          </div>
        </div>
      </section>

      {/* Contact Form & Info Section */}
      <section className="py-20 bg-white dark:bg-[#1a1f1e]">
        <div className="container mx-auto px-4">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12">
            {/* Contact Form */}
            <div className="bg-cream-50 dark:bg-[#2a3330] rounded-2xl p-8">
              <div className="flex items-center mb-6">
                <ChatBubbleLeftIcon className="h-8 w-8 text-sage-600 dark:text-sage-400 mr-3" />
                <h2 className="text-2xl font-bold text-forest-900 dark:text-[#E8EDE8]">
                  {locale === 'sv' ? 'Skicka ett Meddelande' : 'Send us a Message'}
                </h2>
              </div>

              {submitted ? (
                <div className="bg-green-50 border border-green-200 rounded-lg p-6 text-center">
                  <div className="text-green-600 text-4xl mb-4">✓</div>
                  <h3 className="text-lg font-semibold text-green-800 mb-2">
                    {locale === 'sv' ? 'Tack för ditt meddelande!' : 'Thank you for your message!'}
                  </h3>
                  <p className="text-green-700">
                    {locale === 'sv' 
                      ? 'Vi återkommer till dig inom 24 timmar.'
                      : 'We\'ll get back to you within 24 hours.'
                    }
                  </p>
                </div>
              ) : (
                <form onSubmit={handleSubmit} className="space-y-6">
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    <div>
                      <label className="block text-sm font-medium text-forest-700 dark:text-[#B8C5B8] mb-2">
                        {locale === 'sv' ? 'Namn' : 'Name'} *
                      </label>
                      <input
                        type="text"
                        name="name"
                        required
                        value={formData.name}
                        onChange={handleChange}
                        className="w-full px-4 py-3 border border-cream-300 dark:border-[#4a5552] rounded-lg focus:outline-none focus:ring-2 focus:ring-sage-500 dark:focus:ring-sage-600 focus:border-transparent bg-white dark:bg-[#343c39] text-forest-900 dark:text-[#E8EDE8]"
                        placeholder={locale === 'sv' ? 'Ditt namn' : 'Your name'}
                      />
                    </div>
                    <div>
                      <label className="block text-sm font-medium text-forest-700 dark:text-[#B8C5B8] mb-2">
                        {locale === 'sv' ? 'E-post' : 'Email'} *
                      </label>
                      <input
                        type="email"
                        name="email"
                        required
                        value={formData.email}
                        onChange={handleChange}
                        className="w-full px-4 py-3 border border-cream-300 dark:border-[#4a5552] rounded-lg focus:outline-none focus:ring-2 focus:ring-sage-500 dark:focus:ring-sage-600 focus:border-transparent bg-white dark:bg-[#343c39] text-forest-900 dark:text-[#E8EDE8]"
                        placeholder={locale === 'sv' ? 'din@email.se' : 'your@email.com'}
                      />
                    </div>
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-forest-700 dark:text-[#B8C5B8] mb-2">
                      {locale === 'sv' ? 'Ämne' : 'Subject'} *
                    </label>
                    <select
                      name="subject"
                      required
                      value={formData.subject}
                      onChange={handleChange}
                      className="w-full px-4 py-3 border border-cream-300 dark:border-[#4a5552] rounded-lg focus:outline-none focus:ring-2 focus:ring-sage-500 dark:focus:ring-sage-600 focus:border-transparent bg-white dark:bg-[#343c39] text-forest-900 dark:text-[#E8EDE8]"
                    >
                      <option value="">
                        {locale === 'sv' ? 'Välj ämne' : 'Choose subject'}
                      </option>
                      <option value="product">
                        {locale === 'sv' ? 'Produktfråga' : 'Product Question'}
                      </option>
                      <option value="order">
                        {locale === 'sv' ? 'Beställningsfråga' : 'Order Question'}
                      </option>
                      <option value="shipping">
                        {locale === 'sv' ? 'Leveransfråga' : 'Shipping Question'}
                      </option>
                      <option value="return">
                        {locale === 'sv' ? 'Retur/Reklamation' : 'Return/Complaint'}
                      </option>
                      <option value="other">
                        {locale === 'sv' ? 'Annat' : 'Other'}
                      </option>
                    </select>
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-forest-700 dark:text-[#B8C5B8] mb-2">
                      {locale === 'sv' ? 'Meddelande' : 'Message'} *
                    </label>
                    <textarea
                      name="message"
                      required
                      rows={5}
                      value={formData.message}
                      onChange={handleChange}
                      className="w-full px-4 py-3 border border-cream-300 dark:border-[#4a5552] rounded-lg focus:outline-none focus:ring-2 focus:ring-sage-500 dark:focus:ring-sage-600 focus:border-transparent bg-white dark:bg-[#343c39] text-forest-900 dark:text-[#E8EDE8]"
                      placeholder={locale === 'sv' ? 'Skriv ditt meddelande här...' : 'Write your message here...'}
                    />
                  </div>

                  {error && (
                    <div className="bg-red-50 border border-red-200 rounded-lg p-4 text-red-700 text-sm">
                      {error}
                    </div>
                  )}

                  <button
                    type="submit"
                    disabled={isSubmitting}
                    className="w-full px-6 py-3 bg-gradient-to-r from-sage-600 to-sage-700 dark:from-sage-700 dark:to-sage-800 text-white dark:text-[#E8EDE8] font-semibold rounded-lg hover:from-sage-700 hover:to-sage-800 dark:hover:from-sage-800 dark:hover:to-sage-900 transition-all duration-200 disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    {isSubmitting 
                      ? (locale === 'sv' ? 'Skickar...' : 'Sending...')
                      : (locale === 'sv' ? 'Skicka Meddelande' : 'Send Message')
                    }
                  </button>
                </form>
              )}
            </div>

            {/* Contact Information */}
            <div className="space-y-8">
              <div>
                <h2 className="text-2xl font-bold text-forest-900 dark:text-[#E8EDE8] mb-6">
                  {locale === 'sv' ? 'Kontaktuppgifter' : 'Contact Information'}
                </h2>
                <div className="space-y-6">
                  {contactInfo.map((info, index) => (
                    <div key={index} className="flex items-start">
                      <div className="flex-shrink-0">
                        <div className="w-12 h-12 bg-sage-100 dark:bg-[#3f4946] rounded-lg flex items-center justify-center">
                          <info.icon className="h-6 w-6 text-sage-600 dark:text-sage-400" />
                        </div>
                      </div>
                      <div className="ml-4">
                        <h3 className="text-lg font-semibold text-forest-900 dark:text-[#E8EDE8] mb-1">
                          {info.title}
                        </h3>
                        <p className="text-forest-600 dark:text-[#B8C5B8] whitespace-pre-line">
                          {info.content}
                        </p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Online Only Benefits */}
              <div className="bg-gradient-to-br from-sage-50 to-yellow-50 dark:from-[#2a3330] dark:to-[#343c39] rounded-xl p-8">
                <div className="text-center mb-6">
                  <div className="w-16 h-16 bg-sage-100 dark:bg-[#3f4946] rounded-full flex items-center justify-center mx-auto mb-4">
                    <MapPinIcon className="h-8 w-8 text-sage-600 dark:text-sage-400" />
                  </div>
                  <h3 className="text-2xl font-bold text-forest-900 dark:text-[#E8EDE8] mb-2">
                    {locale === 'sv' ? 'Endast Online' : 'Online Only'}
                  </h3>
                  <p className="text-forest-600 dark:text-[#B8C5B8]">
                    {locale === 'sv'
                      ? 'Vi är en digital butik baserad i Göteborg'
                      : 'We are a digital store based in Gothenburg'
                    }
                  </p>
                </div>

                <div className="space-y-4">
                  <div className="flex items-start">
                    <div className="flex-shrink-0 w-6 h-6 bg-sage-600 dark:bg-sage-600 rounded-full flex items-center justify-center mt-0.5">
                      <span className="text-white dark:text-[#E8EDE8] text-sm">✓</span>
                    </div>
                    <p className="ml-3 text-forest-700 dark:text-[#B8C5B8]">
                      {locale === 'sv'
                        ? 'Lägre priser tack vare färre omkostnader'
                        : 'Lower prices thanks to reduced overhead costs'
                      }
                    </p>
                  </div>
                  <div className="flex items-start">
                    <div className="flex-shrink-0 w-6 h-6 bg-sage-600 dark:bg-sage-600 rounded-full flex items-center justify-center mt-0.5">
                      <span className="text-white dark:text-[#E8EDE8] text-sm">✓</span>
                    </div>
                    <p className="ml-3 text-forest-700 dark:text-[#B8C5B8]">
                      {locale === 'sv'
                        ? 'Handla när det passar dig, 24/7'
                        : 'Shop whenever it suits you, 24/7'
                      }
                    </p>
                  </div>
                  <div className="flex items-start">
                    <div className="flex-shrink-0 w-6 h-6 bg-sage-600 dark:bg-sage-600 rounded-full flex items-center justify-center mt-0.5">
                      <span className="text-white dark:text-[#E8EDE8] text-sm">✓</span>
                    </div>
                    <p className="ml-3 text-forest-700 dark:text-[#B8C5B8]">
                      {locale === 'sv'
                        ? 'Snabb leverans till hela Sverige'
                        : 'Fast delivery throughout Sweden'
                      }
                    </p>
                  </div>
                  <div className="flex items-start">
                    <div className="flex-shrink-0 w-6 h-6 bg-sage-600 dark:bg-sage-600 rounded-full flex items-center justify-center mt-0.5">
                      <span className="text-white dark:text-[#E8EDE8] text-sm">✓</span>
                    </div>
                    <p className="ml-3 text-forest-700 dark:text-[#B8C5B8]">
                      {locale === 'sv'
                        ? 'Hållbart och miljövänligt utan fysisk butik'
                        : 'Sustainable and eco-friendly without physical store'
                      }
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* FAQ Link Section */}
      <section className="py-20 bg-cream-50 dark:bg-[#242a28]">
        <div className="container mx-auto px-4">
          <div className="max-w-3xl mx-auto">
            <div className="bg-gradient-to-br from-sage-50 to-yellow-50 dark:from-[#2a3330] dark:to-[#343c39] rounded-2xl p-12 text-center">
              <div className="flex items-center justify-center mb-6">
                <QuestionMarkCircleIcon className="h-12 w-12 text-sage-600 dark:text-sage-400" />
              </div>
              <h2 className="text-3xl font-bold text-forest-900 dark:text-[#E8EDE8] mb-4">
                {locale === 'sv' ? 'Har du frågor?' : 'Have Questions?'}
              </h2>
              <p className="text-lg text-forest-600 dark:text-[#B8C5B8] mb-8 max-w-2xl mx-auto">
                {locale === 'sv'
                  ? 'Besök vår FAQ-sida för svar på vanliga frågor om våra produkter, leverans, returer och mycket mer.'
                  : 'Visit our FAQ page for answers to common questions about our products, delivery, returns and more.'
                }
              </p>
              <Link
                href="/faq"
                className="inline-flex items-center px-8 py-4 bg-gradient-to-r from-sage-600 to-sage-700 dark:from-sage-700 dark:to-sage-800 text-white dark:text-[#E8EDE8] font-semibold rounded-lg hover:from-sage-700 hover:to-sage-800 dark:hover:from-sage-800 dark:hover:to-sage-900 transition-all duration-200 shadow-lg hover:shadow-xl"
              >
                <QuestionMarkCircleIcon className="h-5 w-5 mr-2" />
                {locale === 'sv' ? 'Besök FAQ-sidan' : 'Visit FAQ Page'}
              </Link>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
