// src/components/theme/ThemeToggle.tsx
'use client';

import { useTheme } from '@/contexts/ThemeContext';
import { SunIcon, MoonIcon } from '@heroicons/react/24/outline';

export function ThemeToggle() {
  const { theme, toggleTheme } = useTheme();

  return (
    <button
      onClick={toggleTheme}
      className="relative p-2 rounded-full hover:bg-sage-100 dark:hover:bg-sage-900 transition-colors"
      aria-label={theme === 'light' ? 'Switch to dark mode' : 'Switch to light mode'}
    >
      {theme === 'light' ? (
        <MoonIcon className="h-6 w-6 text-forest-700 dark:text-sage-300" />
      ) : (
        <SunIcon className="h-6 w-6 text-sage-300" />
      )}
    </button>
  );
}

// sveltekit/src/lib/components/theme/ThemeToggle.svelte
<script lang="ts">
	import { Sun, Moon } from 'lucide-svelte';
	import { theme } from '$lib/stores/theme';
</script>

<button
	on:click={() => theme.toggle()}
	class="p-2 text-forest-600 hover:text-forest-900 dark:text-[#B8C5B8] dark:hover:text-[#E8EDE8] transition-colors"
	aria-label="Toggle theme"
>
	{#if $theme === 'dark'}
		<Sun class="h-6 w-6" />
	{:else}
		<Moon class="h-6 w-6" />
	{/if}
</button>
