// sveltekit/src/lib/components/checkout/CheckoutForm.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { goto } from '$app/navigation';
	import { cart } from '$lib/stores/cart';
	import { toast } from '$lib/stores/toast';
	import { page } from '$app/stores';

	export let locale: 'sv' | 'en' = 'sv';
	export let onSuccess: () => void = () => {};

	let step = 1;
	let cartData: any = null;
	let loading = true;
	let processing = false;

	let address = { firstName: '', lastName: '', email: '', phone: '', street: '', city: '', postalCode: '', country: 'SE' };
	let selectedShipping: any = null;
	let shippingOptions: any[] = [];
	let loadingShipping = false;
	let paymentIntentId = '';
	let sessionId = '';

	onMount(async () => {
		sessionId = localStorage.getItem('sessionId') || '';
		const headers: HeadersInit = { 'Content-Type': 'application/json' };
		if (sessionId) headers['x-session-id'] = sessionId;

		try {
			const res = await fetch('/api/checkout', {
				method: 'POST',
				headers,
				body: JSON.stringify({ action: 'validate-cart' }),
			});
			const data = await res.json();
			if (data.success) cartData = data.data;
			else toast.error(locale === 'sv' ? 'Kunde inte validera varukorgen' : 'Failed to validate cart');
		} finally {
			loading = false;
		}
	});

	async function calculateShipping() {
		if (!address.postalCode || !address.country) return;
		loadingShipping = true;
		try {
			const res = await fetch('/api/checkout', {
				method: 'POST',
				headers: { 'Content-Type': 'application/json' },
				body: JSON.stringify({ action: 'calculate-shipping', cartId: cartData?.cart?.id, address }),
			});
			const data = await res.json();
			if (data.success) shippingOptions = data.data?.options ?? [];
		} finally {
			loadingShipping = false;
		}
	}

	async function processPayment() {
		if (!selectedShipping || !cartData) return;
		processing = true;
		try {
			const total = (cartData.cart?.total ?? 0) + (selectedShipping.price ?? 0);
			const piRes = await fetch('/api/checkout', {
				method: 'POST',
				headers: { 'Content-Type': 'application/json' },
				body: JSON.stringify({ action: 'create-payment-intent', amount: Math.round(total * 100), currency: 'sek' }),
			});
			const piData = await piRes.json();
			if (!piData.success) { toast.error('Payment setup failed'); return; }

			const payRes = await fetch('/api/checkout', {
				method: 'POST',
				headers: { 'Content-Type': 'application/json' },
				body: JSON.stringify({
					action: 'process-payment',
					paymentIntentId: piData.data?.id,
					cartId: cartData.cart?.id,
					shippingOption: selectedShipping,
					address,
					customerId: $page.data.session?.user?.id,
					sessionId,
				}),
			});
			const payData = await payRes.json();
			if (payData.success) {
				await cart.refresh();
				goto(`/checkout/success?orderId=${payData.data?.orderId ?? ''}`);
				onSuccess();
			} else {
				toast.error(payData.error ?? (locale === 'sv' ? 'Betalning misslyckades' : 'Payment failed'));
			}
		} finally {
			processing = false;
		}
	}
</script>

{#if loading}
	<div class="flex justify-center py-16"><div class="w-10 h-10 border-4 border-sage-600 border-t-transparent rounded-full animate-spin"></div></div>
{:else if !cartData}
	<div class="text-center py-16">
		<p class="text-forest-600 dark:text-[#B8C5B8] mb-4">{locale === 'sv' ? 'Din varukorg är tom' : 'Your cart is empty'}</p>
		<a href="/products" class="px-6 py-3 bg-sage-600 text-white rounded-full hover:bg-sage-700 transition-colors">
			{locale === 'sv' ? 'Handla nu' : 'Shop now'}
		</a>
	</div>
{:else}
	<div class="grid grid-cols-1 lg:grid-cols-3 gap-8">
		<!-- Left: Form -->
		<div class="lg:col-span-2 space-y-6">
			{#if step === 1}
				<!-- Delivery Address -->
				<div class="bg-white dark:bg-[#2a3330] rounded-2xl p-6 shadow-soft">
					<h2 class="text-xl font-semibold text-forest-800 dark:text-[#E8EDE8] mb-4">{locale === 'sv' ? 'Leveransadress' : 'Delivery Address'}</h2>
					<div class="grid grid-cols-2 gap-4">
						{#each [['firstName', locale === 'sv' ? 'Förnamn' : 'First name'], ['lastName', locale === 'sv' ? 'Efternamn' : 'Last name']] as [field, label]}
							<div>
								<label class="block text-sm font-medium text-forest-700 dark:text-[#C5D4C5] mb-1">{label}</label>
								<input bind:value={address[field]} class="w-full px-3 py-2 border border-cream-300 dark:border-[#4a5552] rounded-lg bg-white dark:bg-[#343c39] dark:text-[#E8EDE8]" />
							</div>
						{/each}
					</div>
					<div class="grid grid-cols-1 gap-4 mt-4">
						{#each [['email', locale === 'sv' ? 'E-post' : 'Email', 'email'], ['phone', locale === 'sv' ? 'Telefon' : 'Phone', 'tel'], ['street', locale === 'sv' ? 'Gatuadress' : 'Street', 'text'], ['city', locale === 'sv' ? 'Stad' : 'City', 'text'], ['postalCode', locale === 'sv' ? 'Postnummer' : 'Postal code', 'text']] as [field, label, type]}
							<div>
								<label class="block text-sm font-medium text-forest-700 dark:text-[#C5D4C5] mb-1">{label}</label>
								<input type={type} bind:value={address[field]} class="w-full px-3 py-2 border border-cream-300 dark:border-[#4a5552] rounded-lg bg-white dark:bg-[#343c39] dark:text-[#E8EDE8]" />
							</div>
						{/each}
					</div>
					<button on:click={() => { step = 2; calculateShipping(); }} class="mt-6 w-full py-3 bg-sage-600 hover:bg-sage-700 text-white rounded-full font-medium transition-colors">
						{locale === 'sv' ? 'Välj frakt' : 'Choose shipping'}
					</button>
				</div>
			{:else if step === 2}
				<!-- Shipping -->
				<div class="bg-white dark:bg-[#2a3330] rounded-2xl p-6 shadow-soft">
					<h2 class="text-xl font-semibold text-forest-800 dark:text-[#E8EDE8] mb-4">{locale === 'sv' ? 'Fraktalternativ' : 'Shipping options'}</h2>
					{#if loadingShipping}
						<div class="flex justify-center py-8"><div class="w-8 h-8 border-4 border-sage-600 border-t-transparent rounded-full animate-spin"></div></div>
					{:else if shippingOptions.length === 0}
						<p class="text-forest-600 dark:text-[#B8C5B8]">{locale === 'sv' ? 'Inga fraktalternativ tillgängliga' : 'No shipping options available'}</p>
					{:else}
						<div class="space-y-3">
							{#each shippingOptions as option}
								<label class="flex items-center gap-4 p-4 rounded-xl border-2 cursor-pointer transition-all {selectedShipping?.id === option.id ? 'border-sage-600 bg-sage-50 dark:bg-sage-900/20' : 'border-cream-200 dark:border-[#4a5552]'}">
									<input type="radio" bind:group={selectedShipping} value={option} class="hidden" />
									<div class="flex-1">
										<p class="font-medium text-forest-800 dark:text-[#E8EDE8]">{option.name}</p>
										<p class="text-sm text-forest-600 dark:text-[#B8C5B8]">{option.estimatedDays}</p>
									</div>
									<span class="font-semibold text-forest-800 dark:text-[#E8EDE8]">
										{option.price === 0 ? (locale === 'sv' ? 'Gratis' : 'Free') : `${option.price} kr`}
									</span>
								</label>
							{/each}
						</div>
					{/if}
					<div class="flex gap-3 mt-6">
						<button on:click={() => step = 1} class="flex-1 py-3 border border-cream-300 dark:border-[#4a5552] rounded-full text-forest-700 dark:text-[#C5D4C5] hover:bg-cream-100 dark:hover:bg-[#343c39] transition-colors">
							{locale === 'sv' ? 'Tillbaka' : 'Back'}
						</button>
						<button on:click={processPayment} disabled={!selectedShipping || processing} class="flex-1 py-3 bg-sage-600 hover:bg-sage-700 text-white rounded-full font-medium transition-colors disabled:opacity-50">
							{processing ? '...' : (locale === 'sv' ? 'Betala' : 'Pay now')}
						</button>
					</div>
				</div>
			{/if}
		</div>

		<!-- Right: Order Summary -->
		<div class="bg-white dark:bg-[#2a3330] rounded-2xl p-6 shadow-soft h-fit">
			<h3 class="font-semibold text-forest-800 dark:text-[#E8EDE8] mb-4">{locale === 'sv' ? 'Din order' : 'Your order'}</h3>
			<div class="space-y-3 mb-4">
				{#each cartData.cart?.items ?? [] as item}
					<div class="flex justify-between text-sm">
						<span class="text-forest-700 dark:text-[#C5D4C5]">{item.product?.name ?? 'Produkt'} × {item.quantity}</span>
						<span class="font-medium text-forest-800 dark:text-[#E8EDE8]">{(item.price * item.quantity).toFixed(2)} kr</span>
					</div>
				{/each}
			</div>
			<div class="border-t border-cream-200 dark:border-[#4a5552] pt-4 flex justify-between font-bold text-forest-800 dark:text-[#E8EDE8]">
				<span>{locale === 'sv' ? 'Totalt' : 'Total'}</span>
				<span>{cartData.cart?.total?.toFixed(2)} kr</span>
			</div>
		</div>
	</div>
{/if}

// src/components/checkout/CheckoutForm.tsx
'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { useAuth } from '@/hooks/useAuth';
import { useCartStore } from '@/stores/cartStore';
import { Address, PaymentMethod, ShippingRate } from '@/types';
import { PriceCalculator } from '@/utils/helpers';
import { 
  CreditCardIcon, 
  BanknotesIcon, 
  DevicePhoneMobileIcon,
  BuildingLibraryIcon 
} from '@heroicons/react/24/outline';

const checkoutSchema = z.object({
  email: z.string().email('Invalid email address'),
  firstName: z.string().min(1, 'First name is required'),
  lastName: z.string().min(1, 'Last name is required'),
  phone: z.string().optional(),
  shippingAddress: z.object({
    street: z.string().min(1, 'Street address is required'),
    city: z.string().min(1, 'City is required'),
    postalCode: z.string().regex(/^\d{3}\s?\d{2}$/, 'Invalid Swedish postal code'),
    country: z.string().default('Sweden'),
  }),
  billingAddress: z.object({
    street: z.string().min(1, 'Street address is required'),
    city: z.string().min(1, 'City is required'),
    postalCode: z.string().regex(/^\d{3}\s?\d{2}$/, 'Invalid Swedish postal code'),
    country: z.string().default('Sweden'),
  }),
  paymentMethod: z.enum(['card', 'swish', 'klarna', 'bank-transfer']),
  sameAddress: z.boolean().default(true),
  marketingOptIn: z.boolean().default(false),
  termsAccepted: z.literal(true, { errorMap: () => ({ message: 'You must accept the terms and conditions' }) }),
});

type CheckoutFormData = z.infer<typeof checkoutSchema>;

interface CheckoutFormProps {
  locale?: 'sv' | 'en';
  onSuccess?: (orderId: string) => void;
}

export const CheckoutForm = ({ locale = 'sv', onSuccess }: CheckoutFormProps) => {
  const router = useRouter();
  const { user, isAuthenticated } = useAuth();
  const { items, total, clearCart } = useCartStore();
  
  const [step, setStep] = useState(1);
  const [isProcessing, setIsProcessing] = useState(false);
  const [shippingRates, setShippingRates] = useState<ShippingRate[]>([]);
  const [selectedShipping, setSelectedShipping] = useState<ShippingRate | null>(null);
  const [availablePaymentMethods, setAvailablePaymentMethods] = useState<PaymentMethod[]>([]);

  const {
    register,
    handleSubmit,
    watch,
    setValue,
    formState: { errors },
  } = useForm<CheckoutFormData>({
    resolver: zodResolver(checkoutSchema),
    defaultValues: {
      email: user?.email || '',
      firstName: user?.firstName || '',
      lastName: user?.lastName || '',
      shippingAddress: {
        street: user?.address?.street || '',
        city: user?.address?.city || '',
        postalCode: user?.address?.postalCode || '',
        country: 'Sweden',
      },
      billingAddress: {
        street: user?.address?.street || '',
        city: user?.address?.city || '',
        postalCode: user?.address?.postalCode || '',
        country: 'Sweden',
      },
      sameAddress: true,
      paymentMethod: 'card',
    },
  });

  const watchedFields = watch(['shippingAddress', 'sameAddress']);

  // Auto-fill billing address when "same address" is checked
  useEffect(() => {
    if (watchedFields[1]) { // sameAddress
      const shippingAddr = watchedFields[0]; // shippingAddress
      setValue('billingAddress', shippingAddr);
    }
  }, [watchedFields, setValue]);

  // Fetch shipping rates when shipping address changes
  useEffect(() => {
    const fetchShippingRates = async () => {
      if (watchedFields[0]?.country && items.length > 0) {
        try {
          const response = await fetch('/api/checkout', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              action: 'calculate-shipping',
              items,
              country: watchedFields[0].country,
              address: watchedFields[0],
            }),
          });

          const result = await response.json();
          if (result.success) {
            setShippingRates(result.data.options);
            setSelectedShipping(result.data.recommended);
          }
        } catch (error) {
          console.error('Failed to fetch shipping rates:', error);
        }
      }
    };

    fetchShippingRates();
  }, [watchedFields[0]?.country, items]);

  // Fetch available payment methods
  useEffect(() => {
    const fetchPaymentMethods = async () => {
      try {
        const response = await fetch('/api/checkout?action=payment-methods');
        const result = await response.json();
        
        if (result.success) {
          setAvailablePaymentMethods(result.data);
        }
      } catch (error) {
        console.error('Failed to fetch payment methods:', error);
      }
    };

    fetchPaymentMethods();
  }, []);

  const onSubmit = async (data: CheckoutFormData) => {
    if (!selectedShipping) {
      alert(locale === 'sv' ? 'Välj ett leveransalternativ' : 'Please select a shipping option');
      return;
    }

    setIsProcessing(true);

    try {
      const orderData = {
        customerId: user?.id || 'guest',
        items,
        shippingAddress: data.shippingAddress,
        billingAddress: data.billingAddress,
        paymentMethod: data.paymentMethod,
        shippingRateId: selectedShipping.id,
      };

      const response = await fetch('/api/checkout', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          action: 'process-payment',
          ...orderData,
        }),
      });

      const result = await response.json();

      if (result.success) {
        // Clear cart after successful order
        await clearCart();
        
        // Redirect based on payment method
        if (result.data.payment.redirectUrl) {
          window.location.href = result.data.payment.redirectUrl;
        } else {
          onSuccess?.(result.data.order.id);
          router.push('/checkout/success');
        }
      } else {
        alert(result.error || (locale === 'sv' ? 'Betalning misslyckades' : 'Payment failed'));
      }
    } catch (error) {
      console.error('Checkout error:', error);
      alert(locale === 'sv' ? 'Ett fel uppstod' : 'An error occurred');
    } finally {
      setIsProcessing(false);
    }
  };

  const getPaymentIcon = (method: PaymentMethod) => {
    switch (method) {
      case 'card':
        return CreditCardIcon;
      case 'swish':
        return DevicePhoneMobileIcon;
      case 'klarna':
        return BanknotesIcon;
      case 'bank-transfer':
        return BuildingLibraryIcon;
      default:
        return CreditCardIcon;
    }
  };

  const getPaymentMethodName = (method: PaymentMethod) => {
    const names = {
      card: locale === 'sv' ? 'Kort' : 'Card',
      swish: 'Swish',
      klarna: 'Klarna',
      'bank-transfer': locale === 'sv' ? 'Bankgiro' : 'Bank Transfer',
    };
    return names[method];
  };

  const subtotal = total;
  const tax = PriceCalculator.calculateVAT(subtotal);
  const shipping = selectedShipping?.price || 0;
  const totalAmount = subtotal + tax + shipping;

  if (items.length === 0) {
    return (
      <div className="text-center py-12">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">
          {locale === 'sv' ? 'Din varukorg är tom' : 'Your cart is empty'}
        </h2>
        <p className="text-gray-600 mb-6">
          {locale === 'sv' 
            ? 'Lägg till produkter innan du går till kassan'
            : 'Add products before proceeding to checkout'
          }
        </p>
        <button
          onClick={() => router.push('/products')}
          className="px-6 py-3 bg-purple-600 text-white rounded-lg hover:bg-purple-700 transition-colors"
        >
          {locale === 'sv' ? 'Handla produkter' : 'Shop products'}
        </button>
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto">
      <form onSubmit={handleSubmit(onSubmit)} className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {/* Left Column - Form */}
        <div className="space-y-6">
          {/* Contact Information */}
          <div className="bg-white p-6 rounded-lg shadow-sm border border-gray-200">
            <h3 className="text-lg font-semibold mb-4">
              {locale === 'sv' ? 'Kontaktuppgifter' : 'Contact Information'}
            </h3>
            
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  {locale === 'sv' ? 'E-post' : 'Email'}
                </label>
                <input
                  {...register('email')}
                  type="email"
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent"
                  placeholder={locale === 'sv' ? 'din@epost.se' : 'your@email.com'}
                />
                {errors.email && (
                  <p className="text-sm text-red-600 mt-1">{errors.email.message}</p>
                )}
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    {locale === 'sv' ? 'Förnamn' : 'First Name'}
                  </label>
                  <input
                    {...register('firstName')}
                    type="text"
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent"
                  />
                  {errors.firstName && (
                    <p className="text-sm text-red-600 mt-1">{errors.firstName.message}</p>
                  )}
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    {locale === 'sv' ? 'Efternamn' : 'Last Name'}
                  </label>
                  <input
                    {...register('lastName')}
                    type="text"
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent"
                  />
                  {errors.lastName && (
                    <p className="text-sm text-red-600 mt-1">{errors.lastName.message}</p>
                  )}
                </div>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  {locale === 'sv' ? 'Telefon (valfritt)' : 'Phone (optional)'}
                </label>
                <input
                  {...register('phone')}
                  type="tel"
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent"
                  placeholder="+46 70 123 45 67"
                />
              </div>
            </div>
          </div>

          {/* Shipping Address */}
          <div className="bg-white p-6 rounded-lg shadow-sm border border-gray-200">
            <h3 className="text-lg font-semibold mb-4">
              {locale === 'sv' ? 'Leveransadress' : 'Shipping Address'}
            </h3>
            
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  {locale === 'sv' ? 'Gatuadress' : 'Street Address'}
                </label>
                <input
                  {...register('shippingAddress.street')}
                  type="text"
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent"
                  placeholder="Storgatan 1"
                />
                {errors.shippingAddress?.street && (
                  <p className="text-sm text-red-600 mt-1">{errors.shippingAddress.street.message}</p>
                )}
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    {locale === 'sv' ? 'Stad' : 'City'}
                  </label>
                  <input
                    {...register('shippingAddress.city')}
                    type="text"
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent"
                    placeholder="Stockholm"
                  />
                  {errors.shippingAddress?.city && (
                    <p className="text-sm text-red-600 mt-1">{errors.shippingAddress.city.message}</p>
                  )}
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    {locale === 'sv' ? 'Postnummer' : 'Postal Code'}
                  </label>
                  <input
                    {...register('shippingAddress.postalCode')}
                    type="text"
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent"
                    placeholder="123 45"
                  />
                  {errors.shippingAddress?.postalCode && (
                    <p className="text-sm text-red-600 mt-1">{errors.shippingAddress.postalCode.message}</p>
                  )}
                </div>
              </div>
            </div>
          </div>

          {/* Billing Address */}
          <div className="bg-white p-6 rounded-lg shadow-sm border border-gray-200">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-lg font-semibold">
                {locale === 'sv' ? 'Fakturaadress' : 'Billing Address'}
              </h3>
              <label className="flex items-center">
                <input
                  {...register('sameAddress')}
                  type="checkbox"
                  className="rounded border-gray-300 text-purple-600 focus:ring-purple-500"
                />
                <span className="ml-2 text-sm text-gray-600">
                  {locale === 'sv' ? 'Samma som leveransadress' : 'Same as shipping'}
                </span>
              </label>
            </div>
            
            {!watch('sameAddress') && (
              <div className="space-y-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    {locale === 'sv' ? 'Gatuadress' : 'Street Address'}
                  </label>
                  <input
                    {...register('billingAddress.street')}
                    type="text"
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent"
                    placeholder="Storgatan 1"
                  />
                  {errors.billingAddress?.street && (
                    <p className="text-sm text-red-600 mt-1">{errors.billingAddress.street.message}</p>
                  )}
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      {locale === 'sv' ? 'Stad' : 'City'}
                    </label>
                    <input
                      {...register('billingAddress.city')}
                      type="text"
                      className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent"
                      placeholder="Stockholm"
                    />
                    {errors.billingAddress?.city && (
                      <p className="text-sm text-red-600 mt-1">{errors.billingAddress.city.message}</p>
                    )}
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      {locale === 'sv' ? 'Postnummer' : 'Postal Code'}
                    </label>
                    <input
                      {...register('billingAddress.postalCode')}
                      type="text"
                      className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent"
                      placeholder="123 45"
                    />
                    {errors.billingAddress?.postalCode && (
                      <p className="text-sm text-red-600 mt-1">{errors.billingAddress.postalCode.message}</p>
                    )}
                  </div>
                </div>
              </div>
            )}
          </div>

          {/* Shipping Options */}
          {shippingRates.length > 0 && (
            <div className="bg-white p-6 rounded-lg shadow-sm border border-gray-200">
              <h3 className="text-lg font-semibold mb-4">
                {locale === 'sv' ? 'Leveransalternativ' : 'Shipping Options'}
              </h3>
              
              <div className="space-y-3">
                {shippingRates.map((rate) => (
                  <label key={rate.id} className="flex items-center justify-between p-3 border rounded-lg cursor-pointer hover:bg-gray-50">
                    <div className="flex items-center">
                      <input
                        type="radio"
                        name="shipping"
                        value={rate.id}
                        checked={selectedShipping?.id === rate.id}
                        onChange={() => setSelectedShipping(rate)}
                        className="text-purple-600 focus:ring-purple-500"
                      />
                      <div className="ml-3">
                        <p className="font-medium text-gray-900">{rate.name}</p>
                        <p className="text-sm text-gray-600">{rate.description}</p>
                        <p className="text-sm text-gray-500">
                          {locale === 'sv' ? `${rate.estimatedDays} arbetsdagar` : `${rate.estimatedDays} business days`}
                        </p>
                      </div>
                    </div>
                    <div className="text-right">
                      <p className="font-semibold text-gray-900">
                        {rate.price === 0 
                          ? (locale === 'sv' ? 'Gratis' : 'Free')
                          : PriceCalculator.formatPrice(rate.price, locale)
                        }
                      </p>
                    </div>
                  </label>
                ))}
              </div>
            </div>
          )}

          {/* Payment Method */}
          <div className="bg-white p-6 rounded-lg shadow-sm border border-gray-200">
            <h3 className="text-lg font-semibold mb-4">
              {locale === 'sv' ? 'Betalningsmetod' : 'Payment Method'}
            </h3>
            
            <div className="grid grid-cols-2 gap-3">
              {availablePaymentMethods.map((method) => {
                const IconComponent = getPaymentIcon(method);
                return (
                  <label key={method} className="flex items-center p-3 border rounded-lg cursor-pointer hover:bg-gray-50">
                    <input
                      {...register('paymentMethod')}
                      type="radio"
                      value={method}
                      className="text-purple-600 focus:ring-purple-500"
                    />
                    <IconComponent className="h-5 w-5 ml-3 text-gray-600" />
                    <span className="ml-2 text-sm font-medium text-gray-900">
                      {getPaymentMethodName(method)}
                    </span>
                  </label>
                );
              })}
            </div>
          </div>

          {/* Terms and Marketing */}
          <div className="bg-white p-6 rounded-lg shadow-sm border border-gray-200">
            <div className="space-y-4">
              <label className="flex items-start">
                <input
                  {...register('termsAccepted')}
                  type="checkbox"
                  className="mt-1 rounded border-gray-300 text-purple-600 focus:ring-purple-500"
                />
                <span className="ml-2 text-sm text-gray-600">
                  {locale === 'sv' 
                    ? 'Jag accepterar villkoren och GDPR-policyn'
                    : 'I accept the terms and conditions and GDPR policy'
                  }
                </span>
              </label>
              {errors.termsAccepted && (
                <p className="text-sm text-red-600">{errors.termsAccepted.message}</p>
              )}

              <label className="flex items-start">
                <input
                  {...register('marketingOptIn')}
                  type="checkbox"
                  className="mt-1 rounded border-gray-300 text-purple-600 focus:ring-purple-500"
                />
                <span className="ml-2 text-sm text-gray-600">
                  {locale === 'sv' 
                    ? 'Jag vill få marknadsföring och erbjudanden via e-post'
                    : 'I would like to receive marketing and offers via email'
                  }
                </span>
              </label>
            </div>
          </div>
        </div>

        {/* Right Column - Order Summary */}
        <div className="lg:sticky lg:top-4 lg:h-fit">
          <div className="bg-white p-6 rounded-lg shadow-sm border border-gray-200">
            <h3 className="text-lg font-semibold mb-4">
              {locale === 'sv' ? 'Ordersammanfattning' : 'Order Summary'}
            </h3>
            
            <div className="space-y-4 mb-6">
              {items.map((item) => (
                <div key={item.productId} className="flex justify-between items-center">
                  <div>
                    <p className="font-medium text-gray-900">Product {item.quantity}x</p>
                    <p className="text-sm text-gray-600">{PriceCalculator.formatPrice(item.price, locale)} each</p>
                  </div>
                  <p className="font-medium text-gray-900">
                    {PriceCalculator.formatPrice(item.price * item.quantity, locale)}
                  </p>
                </div>
              ))}
            </div>

            <div className="border-t pt-4 space-y-2">
              <div className="flex justify-between text-sm">
                <span>{locale === 'sv' ? 'Subtotal' : 'Subtotal'}</span>
                <span>{PriceCalculator.formatPrice(subtotal, locale)}</span>
              </div>
              
              <div className="flex justify-between text-sm">
                <span>{locale === 'sv' ? 'Moms (25%)' : 'VAT (25%)'}</span>
                <span>{PriceCalculator.formatPrice(tax, locale)}</span>
              </div>
              
              <div className="flex justify-between text-sm">
                <span>{locale === 'sv' ? 'Frakt' : 'Shipping'}</span>
                <span>
                  {shipping === 0 
                    ? (locale === 'sv' ? 'Gratis' : 'Free')
                    : PriceCalculator.formatPrice(shipping, locale)
                  }
                </span>
              </div>
              
              <div className="border-t pt-2 flex justify-between font-bold text-lg">
                <span>{locale === 'sv' ? 'Totalt' : 'Total'}</span>
                <span>{PriceCalculator.formatPrice(totalAmount, locale)}</span>
              </div>
            </div>

            <button
              type="submit"
              disabled={isProcessing || !selectedShipping}
              className="w-full mt-6 px-6 py-3 bg-purple-600 text-white font-medium rounded-lg hover:bg-purple-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
            >
              {isProcessing 
                ? (locale === 'sv' ? 'Bearbetar...' : 'Processing...')
                : (locale === 'sv' ? 'Slutför beställning' : 'Complete Order')
              }
            </button>
          </div>
        </div>
      </form>
    </div>
  );
};
