// sveltekit/src/routes/auth/signup/+page.svelte
<script lang="ts">
	import { signIn } from '@auth/sveltekit/client';
	import { goto } from '$app/navigation';
	import { locale } from '$lib/stores/locale';

	let form = { firstName: '', lastName: '', email: '', phone: '', password: '', confirmPassword: '', acceptTerms: false, newsletter: false };
	let showPassword = false;
	let showConfirm = false;
	let loading = false;
	let errors: Record<string, string> = {};

	function validate() {
		const e: Record<string, string> = {};
		if (!form.firstName.trim()) e.firstName = $locale === 'sv' ? 'Förnamn krävs' : 'First name required';
		if (!form.lastName.trim()) e.lastName = $locale === 'sv' ? 'Efternamn krävs' : 'Last name required';
		if (!form.email || !/\S+@\S+\.\S+/.test(form.email)) e.email = $locale === 'sv' ? 'Ogiltig e-post' : 'Invalid email';
		if (!form.password || form.password.length < 8) e.password = $locale === 'sv' ? 'Minst 8 tecken' : 'Min 8 characters';
		if (form.password !== form.confirmPassword) e.confirmPassword = $locale === 'sv' ? 'Lösenorden matchar inte' : 'Passwords do not match';
		if (!form.acceptTerms) e.acceptTerms = $locale === 'sv' ? 'Acceptera villkoren' : 'Accept terms';
		errors = e;
		return Object.keys(e).length === 0;
	}

	async function handleSubmit() {
		if (!validate()) return;
		loading = true;
		try {
			const res = await fetch('/api/auth/signup', {
				method: 'POST',
				headers: { 'Content-Type': 'application/json' },
				body: JSON.stringify({ firstName: form.firstName, lastName: form.lastName, email: form.email, phone: form.phone, password: form.password, marketingOptIn: form.newsletter }),
			});
			const data = await res.json();
			if (!data.success) { errors.submit = data.error ?? 'Error'; return; }

			const signInResult = await signIn('credentials', { email: form.email, password: form.password, redirect: false });
			if (signInResult?.error) goto('/auth/signin?message=account-created');
			else goto('/');
		} catch {
			errors.submit = $locale === 'sv' ? 'Ett fel uppstod' : 'An error occurred';
		} finally {
			loading = false;
		}
	}
</script>

<svelte:head><title>{$locale === 'sv' ? 'Skapa konto' : 'Create account'} – Fortune Essence</title></svelte:head>

<div class="min-h-screen bg-gradient-to-br from-yellow-50 via-purple-50 to-yellow-50 flex items-center justify-center py-12 px-4">
	<div class="max-w-md w-full space-y-8">
		<div class="text-center">
			<a href="/" class="inline-flex items-center space-x-2 mb-8">
				<div class="w-10 h-10 bg-gradient-to-br from-yellow-400 to-purple-600 rounded-full flex items-center justify-center">
					<span class="text-white font-bold text-sm">FE</span>
				</div>
				<span class="text-2xl font-bold text-forest-900">Fortune Essence</span>
			</a>
			<h2 class="text-3xl font-bold text-forest-900 mb-2">{$locale === 'sv' ? 'Skapa Konto' : 'Create Account'}</h2>
		</div>

		<form on:submit|preventDefault={handleSubmit} class="mt-8 space-y-4">
			<div class="grid grid-cols-2 gap-4">
				{#each [['firstName', $locale === 'sv' ? 'Förnamn' : 'First name'], ['lastName', $locale === 'sv' ? 'Efternamn' : 'Last name']] as [field, label]}
					<div>
						<label class="block text-sm font-medium text-forest-700 mb-1">{label} *</label>
						<input type="text" bind:value={form[field]} required class="block w-full px-3 py-3 border {errors[field] ? 'border-red-300' : 'border-cream-300'} rounded-lg focus:outline-none focus:ring-2 focus:ring-sage-500" />
						{#if errors[field]}<p class="mt-1 text-xs text-red-600">{errors[field]}</p>{/if}
					</div>
				{/each}
			</div>

			{#each [['email', $locale === 'sv' ? 'E-post' : 'Email', 'email'], ['phone', $locale === 'sv' ? 'Telefon (valfritt)' : 'Phone (optional)', 'tel']] as [field, label, type]}
				<div>
					<label class="block text-sm font-medium text-forest-700 mb-1">{label}</label>
					<input type={type} bind:value={form[field]} required={field === 'email'} class="block w-full px-3 py-3 border {errors[field] ? 'border-red-300' : 'border-cream-300'} rounded-lg focus:outline-none focus:ring-2 focus:ring-sage-500" />
					{#if errors[field]}<p class="mt-1 text-xs text-red-600">{errors[field]}</p>{/if}
				</div>
			{/each}

			{#each [['password', $locale === 'sv' ? 'Lösenord' : 'Password', showPassword], ['confirmPassword', $locale === 'sv' ? 'Bekräfta lösenord' : 'Confirm password', showConfirm]] as [field, label, show], i}
				<div>
					<label class="block text-sm font-medium text-forest-700 mb-1">{label} *</label>
					<div class="relative">
						<input type={show ? 'text' : 'password'} bind:value={form[field]} required class="block w-full px-3 py-3 pr-12 border {errors[field] ? 'border-red-300' : 'border-cream-300'} rounded-lg focus:outline-none focus:ring-2 focus:ring-sage-500" />
						<button type="button" on:click={() => i === 0 ? showPassword = !showPassword : showConfirm = !showConfirm} class="absolute inset-y-0 right-3 flex items-center text-forest-400">{show ? '🙈' : '👁'}</button>
					</div>
					{#if errors[field]}<p class="mt-1 text-xs text-red-600">{errors[field]}</p>{/if}
				</div>
			{/each}

			<div class="space-y-3">
				<label class="flex items-start gap-3 cursor-pointer">
					<input type="checkbox" bind:checked={form.acceptTerms} class="mt-0.5 h-4 w-4 text-sage-600 rounded border-cream-300" />
					<span class="text-sm text-forest-700">
						{$locale === 'sv' ? 'Jag accepterar ' : 'I accept the '}
						<a href="/terms" class="text-sage-600 hover:text-sage-500">{$locale === 'sv' ? 'användarvillkoren' : 'terms'}</a>
						{$locale === 'sv' ? ' och ' : ' and '}
						<a href="/privacy" class="text-sage-600 hover:text-sage-500">{$locale === 'sv' ? 'integritetspolicyn' : 'privacy policy'}</a> *
					</span>
				</label>
				{#if errors.acceptTerms}<p class="text-xs text-red-600">{errors.acceptTerms}</p>{/if}

				<label class="flex items-start gap-3 cursor-pointer">
					<input type="checkbox" bind:checked={form.newsletter} class="mt-0.5 h-4 w-4 text-sage-600 rounded border-cream-300" />
					<span class="text-sm text-forest-700">{$locale === 'sv' ? 'Jag vill få nyhetsbrev' : 'I want to receive newsletters'}</span>
				</label>
			</div>

			{#if errors.submit}
				<div class="bg-red-50 border border-red-200 rounded-lg p-3">
					<p class="text-red-600 text-sm">{errors.submit}</p>
				</div>
			{/if}

			<button type="submit" disabled={loading} class="w-full flex justify-center py-3 px-4 text-sm font-medium rounded-lg text-white bg-gradient-to-r from-purple-600 to-purple-700 hover:from-purple-700 hover:to-purple-800 disabled:opacity-50 transition-all">
				{loading ? ($locale === 'sv' ? 'Skapar...' : 'Creating...') : ($locale === 'sv' ? 'Skapa Konto' : 'Create Account')}
			</button>

			<div class="text-center text-sm text-forest-600">
				{$locale === 'sv' ? 'Har du redan ett konto?' : 'Already have an account?'}
				<a href="/auth/signin" class="font-medium text-sage-600 hover:text-sage-500 ml-1">{$locale === 'sv' ? 'Logga in' : 'Sign in'}</a>
			</div>
		</form>
	</div>
</div>

// src/app/auth/signup/page.tsx
'use client';

import { useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { 
  EyeIcon, 
  EyeSlashIcon, 
  EnvelopeIcon, 
  LockClosedIcon,
  UserIcon,
  PhoneIcon,
  ArrowRightIcon,
  CheckIcon 
} from '@heroicons/react/24/outline';
import { useAuth } from '@/hooks/useAuth';
import { useLocale } from '@/contexts/LocaleContext';

export default function SignUpPage() {
  const [formData, setFormData] = useState({
    firstName: '',
    lastName: '',
    email: '',
    phone: '',
    password: '',
    confirmPassword: '',
    acceptTerms: false,
    newsletter: false
  });
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirmPassword, setShowConfirmPassword] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [errors, setErrors] = useState<{[key: string]: string}>({});

  const router = useRouter();
  const { signUp, signIn } = useAuth();
  const { locale } = useLocale();

  const validateForm = () => {
    const newErrors: {[key: string]: string} = {};

    if (!formData.firstName.trim()) {
      newErrors.firstName = locale === 'sv' ? 'Förnamn krävs' : 'First name is required';
    }

    if (!formData.lastName.trim()) {
      newErrors.lastName = locale === 'sv' ? 'Efternamn krävs' : 'Last name is required';
    }

    if (!formData.email.trim()) {
      newErrors.email = locale === 'sv' ? 'E-post krävs' : 'Email is required';
    } else if (!/\S+@\S+\.\S+/.test(formData.email)) {
      newErrors.email = locale === 'sv' ? 'Ogiltig e-postadress' : 'Invalid email address';
    }

    if (!formData.password) {
      newErrors.password = locale === 'sv' ? 'Lösenord krävs' : 'Password is required';
    } else if (formData.password.length < 8) {
      newErrors.password = locale === 'sv' ? 'Lösenordet måste vara minst 8 tecken' : 'Password must be at least 8 characters';
    }

    if (formData.password !== formData.confirmPassword) {
      newErrors.confirmPassword = locale === 'sv' ? 'Lösenorden stämmer inte överens' : 'Passwords do not match';
    }

    if (!formData.acceptTerms) {
      newErrors.acceptTerms = locale === 'sv' ? 'Du måste acceptera villkoren' : 'You must accept the terms';
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!validateForm()) {
      return;
    }

    setIsLoading(true);

    try {
      // Create the account
      const signUpResult = await signUp({
        firstName: formData.firstName,
        lastName: formData.lastName,
        email: formData.email,
        phone: formData.phone,
        password: formData.password,
        marketingOptIn: formData.newsletter,
      });

      if (!signUpResult.success) {
        setErrors({
          submit: locale === 'sv'
            ? 'Det gick inte att skapa kontot. Försök igen.'
            : 'Failed to create account. Please try again.'
        });
        return;
      }

      // Automatically sign in the user after successful signup
      const signInResult = await signIn(formData.email, formData.password);

      if (!signInResult.success) {
        // Account was created but auto-login failed - redirect to signin
        router.push('/auth/signin?message=account-created');
        return;
      }

      // Successfully created account and logged in
      router.push('/');
    } catch (err) {
      setErrors({
        submit: locale === 'sv'
          ? 'Ett oväntat fel uppstod. Försök igen.'
          : 'An unexpected error occurred. Please try again.'
      });
    } finally {
      setIsLoading(false);
    }
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value, type, checked } = e.target;
    setFormData({
      ...formData,
      [name]: type === 'checkbox' ? checked : value
    });
    
    // Clear error when user starts typing
    if (errors[name]) {
      setErrors({
        ...errors,
        [name]: ''
      });
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-yellow-50 via-purple-50 to-yellow-50 flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-md w-full space-y-8">
        {/* Header */}
        <div className="text-center">
          <Link href="/" className="inline-flex items-center space-x-2 mb-8">
            <div className="w-10 h-10 bg-gradient-to-br from-yellow-400 to-purple-600 rounded-full flex items-center justify-center">
              <span className="text-white font-bold text-sm">FE</span>
            </div>
            <span className="text-2xl font-bold text-forest-900">Fortune Essence</span>
          </Link>
          
          <h2 className="text-3xl font-bold text-forest-900 mb-2">
            {locale === 'sv' ? 'Skapa Konto' : 'Create Account'}
          </h2>
          <p className="text-forest-600">
            {locale === 'sv' 
              ? 'Gå med i vår community och upptäck naturens kraft.'
              : 'Join our community and discover the power of nature.'
            }
          </p>
        </div>

        {/* Form */}
        <form className="mt-8 space-y-6" onSubmit={handleSubmit}>
          <div className="space-y-4">
            {/* Name Fields */}
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label htmlFor="firstName" className="block text-sm font-medium text-forest-700 mb-2">
                  {locale === 'sv' ? 'Förnamn' : 'First name'} *
                </label>
                <div className="relative">
                  <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                    <UserIcon className="h-5 w-5 text-forest-400" />
                  </div>
                  <input
                    id="firstName"
                    name="firstName"
                    type="text"
                    required
                    value={formData.firstName}
                    onChange={handleChange}
                    className={`block w-full pl-10 pr-3 py-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-sage-500 focus:border-transparent ${
                      errors.firstName ? 'border-red-300' : 'border-cream-300'
                    }`}
                    placeholder={locale === 'sv' ? 'Anna' : 'John'}
                  />
                </div>
                {errors.firstName && (
                  <p className="mt-1 text-sm text-red-600">{errors.firstName}</p>
                )}
              </div>

              <div>
                <label htmlFor="lastName" className="block text-sm font-medium text-forest-700 mb-2">
                  {locale === 'sv' ? 'Efternamn' : 'Last name'} *
                </label>
                <input
                  id="lastName"
                  name="lastName"
                  type="text"
                  required
                  value={formData.lastName}
                  onChange={handleChange}
                  className={`block w-full px-3 py-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-sage-500 focus:border-transparent ${
                    errors.lastName ? 'border-red-300' : 'border-cream-300'
                  }`}
                  placeholder={locale === 'sv' ? 'Larsson' : 'Doe'}
                />
                {errors.lastName && (
                  <p className="mt-1 text-sm text-red-600">{errors.lastName}</p>
                )}
              </div>
            </div>

            {/* Email Field */}
            <div>
              <label htmlFor="email" className="block text-sm font-medium text-forest-700 mb-2">
                {locale === 'sv' ? 'E-postadress' : 'Email address'} *
              </label>
              <div className="relative">
                <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                  <EnvelopeIcon className="h-5 w-5 text-forest-400" />
                </div>
                <input
                  id="email"
                  name="email"
                  type="email"
                  autoComplete="email"
                  required
                  value={formData.email}
                  onChange={handleChange}
                  className={`block w-full pl-10 pr-3 py-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-sage-500 focus:border-transparent ${
                    errors.email ? 'border-red-300' : 'border-cream-300'
                  }`}
                  placeholder={locale === 'sv' ? 'anna@email.se' : 'john@email.com'}
                />
              </div>
              {errors.email && (
                <p className="mt-1 text-sm text-red-600">{errors.email}</p>
              )}
            </div>

            {/* Phone Field */}
            <div>
              <label htmlFor="phone" className="block text-sm font-medium text-forest-700 mb-2">
                {locale === 'sv' ? 'Telefonnummer' : 'Phone number'} ({locale === 'sv' ? 'valfritt' : 'optional'})
              </label>
              <div className="relative">
                <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                  <PhoneIcon className="h-5 w-5 text-forest-400" />
                </div>
                <input
                  id="phone"
                  name="phone"
                  type="tel"
                  value={formData.phone}
                  onChange={handleChange}
                  className="block w-full pl-10 pr-3 py-3 border border-cream-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-sage-500 focus:border-transparent"
                  placeholder="+46 70 123 45 67"
                />
              </div>
            </div>

            {/* Password Fields */}
            <div>
              <label htmlFor="password" className="block text-sm font-medium text-forest-700 mb-2">
                {locale === 'sv' ? 'Lösenord' : 'Password'} *
              </label>
              <div className="relative">
                <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                  <LockClosedIcon className="h-5 w-5 text-forest-400" />
                </div>
                <input
                  id="password"
                  name="password"
                  type={showPassword ? 'text' : 'password'}
                  required
                  value={formData.password}
                  onChange={handleChange}
                  className={`block w-full pl-10 pr-12 py-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-sage-500 focus:border-transparent ${
                    errors.password ? 'border-red-300' : 'border-cream-300'
                  }`}
                  placeholder={locale === 'sv' ? 'Minst 8 tecken' : 'At least 8 characters'}
                />
                <button
                  type="button"
                  className="absolute inset-y-0 right-0 pr-3 flex items-center"
                  onClick={() => setShowPassword(!showPassword)}
                >
                  {showPassword ? (
                    <EyeSlashIcon className="h-5 w-5 text-forest-400 hover:text-forest-600" />
                  ) : (
                    <EyeIcon className="h-5 w-5 text-forest-400 hover:text-forest-600" />
                  )}
                </button>
              </div>
              {errors.password && (
                <p className="mt-1 text-sm text-red-600">{errors.password}</p>
              )}
            </div>

            <div>
              <label htmlFor="confirmPassword" className="block text-sm font-medium text-forest-700 mb-2">
                {locale === 'sv' ? 'Bekräfta lösenord' : 'Confirm password'} *
              </label>
              <div className="relative">
                <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                  <LockClosedIcon className="h-5 w-5 text-forest-400" />
                </div>
                <input
                  id="confirmPassword"
                  name="confirmPassword"
                  type={showConfirmPassword ? 'text' : 'password'}
                  required
                  value={formData.confirmPassword}
                  onChange={handleChange}
                  className={`block w-full pl-10 pr-12 py-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-sage-500 focus:border-transparent ${
                    errors.confirmPassword ? 'border-red-300' : 'border-cream-300'
                  }`}
                  placeholder={locale === 'sv' ? 'Upprepa lösenordet' : 'Repeat password'}
                />
                <button
                  type="button"
                  className="absolute inset-y-0 right-0 pr-3 flex items-center"
                  onClick={() => setShowConfirmPassword(!showConfirmPassword)}
                >
                  {showConfirmPassword ? (
                    <EyeSlashIcon className="h-5 w-5 text-forest-400 hover:text-forest-600" />
                  ) : (
                    <EyeIcon className="h-5 w-5 text-forest-400 hover:text-forest-600" />
                  )}
                </button>
              </div>
              {errors.confirmPassword && (
                <p className="mt-1 text-sm text-red-600">{errors.confirmPassword}</p>
              )}
            </div>
          </div>

          {/* Checkboxes */}
          <div className="space-y-4">
            <div className="flex items-start">
              <div className="flex items-center h-5">
                <input
                  id="acceptTerms"
                  name="acceptTerms"
                  type="checkbox"
                  checked={formData.acceptTerms}
                  onChange={handleChange}
                  className="h-4 w-4 text-sage-600 focus:ring-sage-500 border-cream-300 rounded"
                />
              </div>
              <div className="ml-3 text-sm">
                <label htmlFor="acceptTerms" className="text-forest-700">
                  {locale === 'sv' ? 'Jag accepterar ' : 'I accept the '}
                  <Link href="/terms" className="text-sage-600 hover:text-sage-500">
                    {locale === 'sv' ? 'användarvillkoren' : 'terms of service'}
                  </Link>
                  {locale === 'sv' ? ' och ' : ' and '}
                  <Link href="/privacy" className="text-sage-600 hover:text-sage-500">
                    {locale === 'sv' ? 'integritetspolicyn' : 'privacy policy'}
                  </Link>
                  *
                </label>
              </div>
            </div>
            {errors.acceptTerms && (
              <p className="text-sm text-red-600">{errors.acceptTerms}</p>
            )}

            <div className="flex items-start">
              <div className="flex items-center h-5">
                <input
                  id="newsletter"
                  name="newsletter"
                  type="checkbox"
                  checked={formData.newsletter}
                  onChange={handleChange}
                  className="h-4 w-4 text-sage-600 focus:ring-sage-500 border-cream-300 rounded"
                />
              </div>
              <div className="ml-3 text-sm">
                <label htmlFor="newsletter" className="text-forest-700">
                  {locale === 'sv' 
                    ? 'Jag vill få nyhetsbrev och specialerbjudanden (kan avmälas när som helst)'
                    : 'I want to receive newsletters and special offers (can unsubscribe anytime)'
                  }
                </label>
              </div>
            </div>
          </div>

          {/* Error Message */}
          {errors.submit && (
            <div className="bg-red-50 border border-red-200 rounded-lg p-4">
              <p className="text-red-600 text-sm">{errors.submit}</p>
            </div>
          )}

          {/* Submit Button */}
          <button
            type="submit"
            disabled={isLoading}
            className="group relative w-full flex justify-center py-3 px-4 border border-transparent text-sm font-medium rounded-lg text-white bg-gradient-to-r from-purple-600 to-purple-700 hover:from-purple-700 hover:to-purple-800 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-sage-500 disabled:opacity-50 disabled:cursor-not-allowed transition-all duration-200"
          >
            {isLoading ? (
              <>
                <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white mr-2"></div>
                {locale === 'sv' ? 'Skapar konto...' : 'Creating account...'}
              </>
            ) : (
              <>
                {locale === 'sv' ? 'Skapa Konto' : 'Create Account'}
                <ArrowRightIcon className="ml-2 h-4 w-4 group-hover:translate-x-1 transition-transform" />
              </>
            )}
          </button>

          {/* Sign In Link */}
          <div className="text-center">
            <p className="text-sm text-forest-600">
              {locale === 'sv' ? 'Har du redan ett konto?' : 'Already have an account?'}{' '}
              <Link
                href="/auth/signin"
                className="font-medium text-sage-600 hover:text-sage-500 transition-colors"
              >
                {locale === 'sv' ? 'Logga in' : 'Sign in'}
              </Link>
            </p>
          </div>
        </form>
      </div>
    </div>
  );
}
