// sveltekit/src/routes/auth/error/+page.svelte
<script lang="ts">
	import { page } from '$app/stores';

	const errorMessages: Record<string, string> = {
		Configuration: 'Det finns ett konfigurationsfel. Kontakta support.',
		AccessDenied: 'Åtkomst nekad. Du har inte behörighet att logga in.',
		Verification: 'Verifieringslänken har löpt ut eller redan använts.',
		Default: 'Ett inloggningsfel inträffade. Försök igen.',
	};

	$: errorCode = $page.url.searchParams.get('error') || 'Default';
	$: message = errorMessages[errorCode] || errorMessages.Default;
</script>

<svelte:head><title>Inloggningsfel – Fortune Essence</title></svelte:head>

<div class="min-h-screen bg-cream-50 dark:bg-[#1a1f1e] flex items-center justify-center px-4">
	<div class="bg-white dark:bg-[#242a28] rounded-2xl shadow-soft p-8 w-full max-w-md text-center border border-transparent dark:border-[#3f4946]">
		<div class="w-16 h-16 bg-red-100 dark:bg-red-900/30 rounded-full flex items-center justify-center mx-auto mb-4">
			<svg class="w-8 h-8 text-red-600 dark:text-red-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
				<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01M12 3a9 9 0 100 18A9 9 0 0012 3z" />
			</svg>
		</div>
		<h1 class="text-2xl font-serif font-bold text-forest-800 dark:text-[#E8EDE8] mb-2">Inloggningsfel</h1>
		<p class="text-forest-600 dark:text-[#C5D4C5] mb-6">{message}</p>
		<div class="flex flex-col gap-3">
			<a href="/auth/signin"
				class="px-6 py-3 bg-sage-600 text-white font-medium rounded-full hover:bg-sage-700 transition-colors">
				Försök igen
			</a>
			<a href="/"
				class="px-6 py-3 border-2 border-cream-300 dark:border-[#3f4946] text-forest-700 dark:text-[#C5D4C5] font-medium rounded-full hover:bg-cream-100 dark:hover:bg-[#2a3330] transition-colors">
				Tillbaka till startsidan
			</a>
		</div>
	</div>
</div>

// src/app/error.tsx
'use client';

import { useEffect } from 'react';
import Link from 'next/link';
import { ExclamationTriangleIcon, ArrowPathIcon, HomeIcon } from '@heroicons/react/24/outline';

export default function Error({
  error,
  reset,
}: {
  error: Error & { digest?: string };
  reset: () => void;
}) {
  const locale = 'sv'; // Would come from context in real app

  useEffect(() => {
    // Log the error to an error reporting service
    console.error('Error boundary caught:', error);
  }, [error]);

  return (
    <div className="min-h-screen bg-cream-50 dark:bg-[#1a1f1e] flex items-center justify-center px-4">
      <div className="max-w-2xl w-full text-center">
        {/* Error Visual */}
        <div className="mb-8">
          <div className="w-24 h-24 mx-auto mb-6 rounded-full bg-red-100 dark:bg-red-900/30 flex items-center justify-center">
            <ExclamationTriangleIcon className="h-12 w-12 text-red-600 dark:text-red-400" />
          </div>
        </div>

        {/* Message */}
        <h1 className="text-4xl lg:text-5xl font-serif font-bold text-forest-800 dark:text-[#E8EDE8] mb-4">
          {locale === 'sv' ? 'Något gick fel' : 'Something went wrong'}
        </h1>
        <p className="text-lg text-forest-600 dark:text-[#C5D4C5] mb-8 max-w-md mx-auto">
          {locale === 'sv'
            ? 'Ett oväntat fel uppstod. Vi har loggat problemet och arbetar på en lösning.'
            : "An unexpected error occurred. We've logged the issue and are working on a fix."
          }
        </p>

        {/* Error Details (only in development) */}
        {process.env.NODE_ENV === 'development' && (
          <div className="mb-8 p-6 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-2xl text-left max-w-2xl mx-auto">
            <p className="font-mono text-sm text-red-800 dark:text-red-300 mb-2">
              <strong>Error:</strong> {error.message}
            </p>
            {error.digest && (
              <p className="font-mono text-xs text-red-600 dark:text-red-400">
                <strong>Digest:</strong> {error.digest}
              </p>
            )}
          </div>
        )}

        {/* Action Buttons */}
        <div className="flex flex-col sm:flex-row gap-4 justify-center mb-12">
          <button
            onClick={reset}
            className="inline-flex items-center justify-center gap-2 px-8 py-4 rounded-full bg-sage-600 text-white font-semibold hover:bg-sage-700 transition-all shadow-lg hover:shadow-xl"
          >
            <ArrowPathIcon className="h-5 w-5" />
            {locale === 'sv' ? 'Försök igen' : 'Try Again'}
          </button>
          <Link
            href="/"
            className="inline-flex items-center justify-center gap-2 px-8 py-4 rounded-full bg-white dark:bg-[#242a28] text-forest-800 dark:text-[#E8EDE8] font-semibold border-2 border-cream-300 dark:border-[#3f4946] hover:border-sage-600 hover:bg-sage-50 dark:hover:bg-[#2a3330] transition-all shadow-lg"
          >
            <HomeIcon className="h-5 w-5" />
            {locale === 'sv' ? 'Tillbaka till startsidan' : 'Back to Home'}
          </Link>
        </div>

        {/* Support Link */}
        <div className="bg-white dark:bg-[#242a28] rounded-3xl shadow-soft p-8">
          <h3 className="font-semibold text-forest-800 dark:text-[#E8EDE8] mb-2">
            {locale === 'sv' ? 'Behöver du hjälp?' : 'Need Help?'}
          </h3>
          <p className="text-forest-600 dark:text-[#C5D4C5] mb-4">
            {locale === 'sv'
              ? 'Om problemet kvarstår, kontakta vår kundservice.'
              : 'If the problem persists, please contact our support team.'
            }
          </p>
          <Link
            href="/contact"
            className="text-sage-700 dark:text-sage-400 hover:text-sage-800 dark:hover:text-sage-300 font-semibold hover:underline transition-colors"
          >
            {locale === 'sv' ? 'Kontakta oss →' : 'Contact Us →'}
          </Link>
        </div>
      </div>
    </div>
  );
}
