// sveltekit/src/routes/auth/reset-password/+page.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import { goto } from '$app/navigation';
	import { locale } from '$lib/stores/locale';
	import { toast } from '$lib/stores/toast';
	import Toast from '$lib/components/ui/Toast.svelte';

	let password = '';
	let confirmPassword = '';
	let submitting = false;
	let success = false;

	$: token = $page.url.searchParams.get('token') ?? '';

	async function handleSubmit() {
		if (password !== confirmPassword) { toast.error($locale === 'sv' ? 'Lösenorden matchar inte' : 'Passwords do not match'); return; }
		if (password.length < 8) { toast.error($locale === 'sv' ? 'Minst 8 tecken' : 'Min 8 characters'); return; }
		submitting = true;
		try {
			const res = await fetch('/api/auth/reset-password', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ token, password }) });
			const data = await res.json();
			if (data.success) { success = true; setTimeout(() => goto('/auth/signin'), 3000); }
			else toast.error(data.error ?? ($locale === 'sv' ? 'Något gick fel' : 'Something went wrong'));
		} catch { toast.error($locale === 'sv' ? 'Fel' : 'Error'); }
		finally { submitting = false; }
	}
</script>

<svelte:head><title>{$locale === 'sv' ? 'Återställ lösenord' : 'Reset password'} – Fortune Essence</title></svelte:head>
<Toast />

<div class="min-h-screen bg-cream-50 flex items-center justify-center px-4 py-12">
	<div class="max-w-md w-full">
		<div class="bg-white rounded-3xl shadow-soft p-8">
			{#if success}
				<div class="text-center">
					<div class="text-5xl mb-4">✅</div>
					<h1 class="text-2xl font-serif font-bold text-forest-800 mb-3">{$locale === 'sv' ? 'Lösenord ändrat!' : 'Password changed!'}</h1>
					<p class="text-forest-600">{$locale === 'sv' ? 'Du omdirigeras till inloggning...' : 'Redirecting to sign in...'}</p>
				</div>
			{:else}
				<h1 class="text-2xl font-serif font-bold text-forest-800 mb-6">{$locale === 'sv' ? 'Nytt lösenord' : 'New Password'}</h1>
				<form on:submit|preventDefault={handleSubmit} class="space-y-5">
					{#each [['password', $locale === 'sv' ? 'Lösenord' : 'Password'], ['confirmPassword', $locale === 'sv' ? 'Bekräfta lösenord' : 'Confirm password']] as [field, label]}
						<div>
							<label class="block text-sm font-medium text-forest-700 mb-2">{label}</label>
							<input type="password" bind:value={field === 'password' ? password : confirmPassword} required minlength={8}
								class="w-full px-4 py-3 rounded-xl border-2 border-cream-300 focus:border-sage-600 focus:outline-none transition-colors" />
						</div>
					{/each}
					<button type="submit" disabled={submitting || !token} class="w-full py-3 bg-sage-600 hover:bg-sage-700 text-white rounded-full font-medium disabled:opacity-50 transition-colors">
						{submitting ? ($locale === 'sv' ? 'Sparar...' : 'Saving...') : ($locale === 'sv' ? 'Spara nytt lösenord' : 'Save new password')}
					</button>
				</form>
			{/if}
		</div>
	</div>
</div>

// src/app/auth/reset-password/page.tsx
'use client';

import { useState, useEffect } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import Link from 'next/link';
import { LockClosedIcon, EyeIcon, EyeSlashIcon } from '@heroicons/react/24/outline';
import toast from 'react-hot-toast';

export default function ResetPasswordPage() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const token = searchParams.get('token');

  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirmPassword, setShowConfirmPassword] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isValidToken, setIsValidToken] = useState(true);
  const locale = 'sv'; // Would come from context in real app

  useEffect(() => {
    if (!token) {
      setIsValidToken(false);
      toast.error(locale === 'sv' ? 'Ogiltig återställningslänk' : 'Invalid reset link');
    }
  }, [token, locale]);

  const validatePassword = (pwd: string) => {
    if (pwd.length < 8) {
      return locale === 'sv'
        ? 'Lösenordet måste vara minst 8 tecken'
        : 'Password must be at least 8 characters';
    }
    if (!/[A-Z]/.test(pwd)) {
      return locale === 'sv'
        ? 'Lösenordet måste innehålla minst en stor bokstav'
        : 'Password must contain at least one uppercase letter';
    }
    if (!/[a-z]/.test(pwd)) {
      return locale === 'sv'
        ? 'Lösenordet måste innehålla minst en liten bokstav'
        : 'Password must contain at least one lowercase letter';
    }
    if (!/[0-9]/.test(pwd)) {
      return locale === 'sv'
        ? 'Lösenordet måste innehålla minst en siffra'
        : 'Password must contain at least one number';
    }
    return null;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    // Validate password
    const passwordError = validatePassword(password);
    if (passwordError) {
      toast.error(passwordError);
      return;
    }

    // Check passwords match
    if (password !== confirmPassword) {
      toast.error(locale === 'sv' ? 'Lösenorden matchar inte' : 'Passwords do not match');
      return;
    }

    if (!token) {
      toast.error(locale === 'sv' ? 'Ogiltig återställningslänk' : 'Invalid reset link');
      return;
    }

    setIsSubmitting(true);
    try {
      const response = await fetch('/api/auth/reset-password', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ token, password }),
      });

      const data = await response.json();

      if (data.success) {
        toast.success(
          locale === 'sv'
            ? 'Lösenordet har återställts! Du kan nu logga in.'
            : 'Password reset successfully! You can now sign in.'
        );
        router.push('/auth/signin');
      } else {
        toast.error(data.error || (locale === 'sv' ? 'Något gick fel' : 'Something went wrong'));
      }
    } catch (error) {
      toast.error(locale === 'sv' ? 'Kunde inte återställa lösenordet' : 'Failed to reset password');
    } finally {
      setIsSubmitting(false);
    }
  };

  if (!isValidToken) {
    return (
      <div className="min-h-screen bg-cream-50 flex items-center justify-center px-4 py-12">
        <div className="max-w-md w-full">
          <div className="bg-white rounded-3xl shadow-soft p-8 lg:p-10 text-center">
            <div className="w-16 h-16 mx-auto mb-6 rounded-full bg-red-100 flex items-center justify-center">
              <LockClosedIcon className="h-8 w-8 text-red-600" />
            </div>
            <h2 className="text-2xl font-serif font-bold text-forest-800 mb-3">
              {locale === 'sv' ? 'Ogiltig länk' : 'Invalid Link'}
            </h2>
            <p className="text-forest-600 mb-6">
              {locale === 'sv'
                ? 'Återställningslänken är ogiltig eller har löpt ut. Vänligen begär en ny.'
                : 'The reset link is invalid or has expired. Please request a new one.'
              }
            </p>
            <Link
              href="/auth/forgot-password"
              className="inline-block px-8 py-3.5 rounded-full bg-sage-600 text-white font-semibold hover:bg-sage-700 transition-all shadow-lg"
            >
              {locale === 'sv' ? 'Begär ny länk' : 'Request New Link'}
            </Link>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-cream-50 flex items-center justify-center px-4 py-12">
      <div className="max-w-md w-full">
        <div className="bg-white rounded-3xl shadow-soft p-8 lg:p-10">
          {/* Icon */}
          <div className="w-16 h-16 mx-auto mb-6 rounded-full bg-sage-100 flex items-center justify-center">
            <LockClosedIcon className="h-8 w-8 text-sage-600" />
          </div>

          {/* Header */}
          <div className="text-center mb-8">
            <h1 className="text-3xl font-serif font-bold text-forest-800 mb-3">
              {locale === 'sv' ? 'Återställ lösenord' : 'Reset Password'}
            </h1>
            <p className="text-forest-600">
              {locale === 'sv'
                ? 'Ange ditt nya lösenord nedan'
                : 'Enter your new password below'
              }
            </p>
          </div>

          {/* Form */}
          <form onSubmit={handleSubmit} className="space-y-6">
            {/* New Password */}
            <div>
              <label htmlFor="password" className="block text-sm font-medium text-forest-700 mb-2">
                {locale === 'sv' ? 'Nytt lösenord' : 'New Password'}
              </label>
              <div className="relative">
                <input
                  type={showPassword ? 'text' : 'password'}
                  id="password"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  className="w-full px-4 py-3.5 pr-12 rounded-2xl border-2 border-cream-300 focus:border-sage-600 focus:outline-none transition-colors"
                  placeholder={locale === 'sv' ? 'Minst 8 tecken' : 'At least 8 characters'}
                  disabled={isSubmitting}
                  required
                />
                <button
                  type="button"
                  onClick={() => setShowPassword(!showPassword)}
                  className="absolute right-4 top-1/2 -translate-y-1/2 text-forest-400 hover:text-forest-600 transition-colors"
                >
                  {showPassword ? (
                    <EyeSlashIcon className="h-5 w-5" />
                  ) : (
                    <EyeIcon className="h-5 w-5" />
                  )}
                </button>
              </div>
              <p className="mt-2 text-xs text-forest-500">
                {locale === 'sv'
                  ? 'Minst 8 tecken, en stor bokstav, en liten bokstav och en siffra'
                  : 'At least 8 characters, one uppercase, one lowercase, and one number'
                }
              </p>
            </div>

            {/* Confirm Password */}
            <div>
              <label htmlFor="confirmPassword" className="block text-sm font-medium text-forest-700 mb-2">
                {locale === 'sv' ? 'Bekräfta lösenord' : 'Confirm Password'}
              </label>
              <div className="relative">
                <input
                  type={showConfirmPassword ? 'text' : 'password'}
                  id="confirmPassword"
                  value={confirmPassword}
                  onChange={(e) => setConfirmPassword(e.target.value)}
                  className="w-full px-4 py-3.5 pr-12 rounded-2xl border-2 border-cream-300 focus:border-sage-600 focus:outline-none transition-colors"
                  placeholder={locale === 'sv' ? 'Ange lösenordet igen' : 'Enter password again'}
                  disabled={isSubmitting}
                  required
                />
                <button
                  type="button"
                  onClick={() => setShowConfirmPassword(!showConfirmPassword)}
                  className="absolute right-4 top-1/2 -translate-y-1/2 text-forest-400 hover:text-forest-600 transition-colors"
                >
                  {showConfirmPassword ? (
                    <EyeSlashIcon className="h-5 w-5" />
                  ) : (
                    <EyeIcon className="h-5 w-5" />
                  )}
                </button>
              </div>
            </div>

            <button
              type="submit"
              disabled={isSubmitting}
              className="w-full py-4 rounded-full bg-sage-600 text-white font-semibold hover:bg-sage-700 transition-all shadow-lg hover:shadow-xl disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {isSubmitting
                ? (locale === 'sv' ? 'Återställer...' : 'Resetting...')
                : (locale === 'sv' ? 'Återställ lösenord' : 'Reset Password')
              }
            </button>
          </form>
        </div>

        {/* Sign In Link */}
        <p className="text-center mt-6 text-forest-600">
          {locale === 'sv' ? 'Kom du ihåg ditt lösenord?' : 'Remember your password?'}{' '}
          <Link href="/auth/signin" className="text-sage-700 font-semibold hover:text-sage-800 hover:underline transition-colors">
            {locale === 'sv' ? 'Logga in' : 'Sign In'}
          </Link>
        </p>
      </div>
    </div>
  );
}
