// sveltekit/src/routes/products/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { page } from '$app/stores';
	import { locale } from '$lib/stores/locale';
	import type { Product, BundleConfiguration } from '$lib/types';
	import ProductGrid from '$lib/components/products/ProductGrid.svelte';
	import ProductFilters from '$lib/components/products/ProductFilters.svelte';
	import BundleCard from '$lib/components/bundles/BundleCard.svelte';
	import { Search } from 'lucide-svelte';

	let allProducts: Product[] = [];
	let bundles: Product[] = [];
	let bundleConfigs: Record<string, BundleConfiguration> = {};
	let filteredProducts: Product[] = [];
	let filterOptions = { categories: [] as any[], priceRange: { min: 0, max: 1000 } };
	let filters: Record<string, unknown> = {};
	let searchQuery = '';
	let loading = true;
	let debounceTimer: ReturnType<typeof setTimeout>;

	$: {
		clearTimeout(debounceTimer);
		debounceTimer = setTimeout(() => applyFilters(), 300);
	}

	onMount(async () => {
		const q = $page.url.searchParams.get('search');
		if (q) searchQuery = q;
		await fetchData();
	});

	async function fetchData() {
		loading = true;
		try {
			const [productsRes, categoriesRes] = await Promise.all([
				fetch(`/api/products?locale=${$locale}`),
				fetch('/api/products/categories'),
			]);
			const productsData = await productsRes.json();
			const categoriesData = await categoriesRes.json();

			if (productsData.success) {
				bundles = productsData.data.filter((p: Product) => p.category === 'bundles');
				allProducts = productsData.data.filter((p: Product) => p.category !== 'bundles');
				filteredProducts = allProducts;

				if (bundles.length > 0) {
					const bundlesRes = await fetch('/api/bundles');
					const bundlesData = await bundlesRes.json();
					if (bundlesData.success) {
						bundlesData.data.forEach((c: BundleConfiguration) => { bundleConfigs[c.bundleProductId] = c; });
					}
				}

				if (productsData.success && categoriesData.success) {
					const prices = productsData.data.map((p: Product) => p.price);
					filterOptions = { categories: categoriesData.data, priceRange: { min: Math.floor(Math.min(...prices)), max: Math.ceil(Math.max(...prices)) } };
				}
			}
		} finally { loading = false; }
	}

	function applyFilters() {
		let f = [...allProducts];
		if (searchQuery) {
			const q = searchQuery.toLowerCase();
			f = f.filter(p => {
				const name = p.translations[$locale]?.name ?? p.name;
				return name.toLowerCase().includes(q) || p.sku.toLowerCase().includes(q);
			});
		}
		if (filters.category) f = f.filter(p => p.category === filters.category);
		if (filters.inStock) f = f.filter(p => p.stock > 0);
		filteredProducts = f;
	}
</script>

<svelte:head><title>{$locale === 'sv' ? 'Alla produkter' : 'All products'} – Fortune Essence</title></svelte:head>

<div class="min-h-screen bg-gradient-to-b from-yellow-50 to-white dark:from-[#1a1f1e] dark:to-[#242a28]">
	<div class="container mx-auto px-4 py-8">
		<div class="mb-8">
			<h1 class="text-3xl font-bold text-forest-900 dark:text-[#E8EDE8] mb-2">{$locale === 'sv' ? 'Alla Produkter' : 'All Products'}</h1>
			<p class="text-forest-600 dark:text-[#B8C5B8]">{$locale === 'sv' ? 'Upptäck vårt fullständiga sortiment av premium eteriska oljor.' : 'Discover our complete range of premium essential oils.'}</p>
		</div>

		<div class="mb-6">
			<div class="relative max-w-md">
				<div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none"><Search size={20} class="text-forest-400 dark:text-[#6B7B6B]" /></div>
				<input type="text" bind:value={searchQuery} placeholder={$locale === 'sv' ? 'Sök produkter...' : 'Search products...'}
					class="block w-full pl-10 pr-3 py-2 border border-cream-300 dark:border-[#4a5552] rounded-md bg-white dark:bg-[#2a3330] dark:text-[#E8EDE8] placeholder-forest-500 dark:placeholder-[#6B7B6B] focus:outline-none focus:ring-1 focus:ring-sage-500" />
			</div>
		</div>

		{#if bundles.length > 0}
			<div class="mb-12">
				<h2 class="text-2xl font-serif font-bold text-forest-800 mb-2">{$locale === 'sv' ? 'Spara med våra paket' : 'Save with our bundles'}</h2>
				<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
					{#each bundles as bundle (bundle.id)}
						{@const config = bundleConfigs[bundle.id]}
						{#if config}
							<BundleCard product={bundle} requiredQuantity={config.requiredQuantity} discountPercentage={config.discountPercentage} locale={$locale} />
						{/if}
					{/each}
				</div>
			</div>
		{/if}

		<div class="mb-4 text-sm text-forest-700 dark:text-[#C5D4C5]">
			{$locale === 'sv' ? `Visar ${filteredProducts.length} av ${allProducts.length} produkter` : `Showing ${filteredProducts.length} of ${allProducts.length} products`}
		</div>

		{#if loading}
			<div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
				{#each [1, 2, 3, 4, 5, 6] as _}
					<div class="h-96 bg-cream-300 dark:bg-[#343c39] rounded-2xl animate-pulse"></div>
				{/each}
			</div>
		{:else}
			<div class="grid grid-cols-1 lg:grid-cols-4 gap-6">
				<div class="lg:col-span-1">
					<ProductFilters locale={$locale} {filters} options={filterOptions} onFiltersChange={f => { filters = f; applyFilters(); }} className="sticky top-4" />
				</div>
				<div class="lg:col-span-3">
					<ProductGrid products={filteredProducts} locale={$locale}
						emptyMessage={searchQuery ? ($locale === 'sv' ? `Inga produkter för "${searchQuery}"` : `No products for "${searchQuery}"`) : ($locale === 'sv' ? 'Inga produkter matchar' : 'No products match')} />
				</div>
			</div>
		{/if}
	</div>
</div>

// src/app/products/page.tsx
'use client';

import { useState, useEffect, useCallback } from 'react';
import { useLocale } from '@/contexts/LocaleContext';
import { Product, BundleConfiguration } from '@/types';
import { ProductGrid } from '@/components/products/ProductGrid';
import { ProductFilters } from '@/components/products/ProductFilters';
import { BundleCard } from '@/components/bundles';
import { MagnifyingGlassIcon } from '@heroicons/react/24/outline';
import { useDebounce } from '@/hooks/useDebounce';

interface FilterOptions {
  categories: { category: string; count: number; displayName: { sv: string; en: string } }[];
  priceRange: { min: number; max: number };
}

interface ActiveFilters {
  category?: string;
  minPrice?: number;
  maxPrice?: number;
  inStock?: boolean;
  sortBy?: 'name' | 'price' | 'created';
  sortOrder?: 'asc' | 'desc';
}

export default function ProductsPage() {
  const [products, setProducts] = useState<Product[]>([]);
  const [bundles, setBundles] = useState<Product[]>([]);
  const [bundleConfigs, setBundleConfigs] = useState<Record<string, BundleConfiguration>>({});
  const [filteredProducts, setFilteredProducts] = useState<Product[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState('');
  const [filters, setFilters] = useState<ActiveFilters>({});
  const [filterOptions, setFilterOptions] = useState<FilterOptions>({
    categories: [],
    priceRange: { min: 0, max: 1000 }
  });
  const { locale } = useLocale();

  const debouncedSearchQuery = useDebounce(searchQuery, 300);

  // Fetch products and filter options
  useEffect(() => {
    const fetchData = async () => {
      setLoading(true);

      try {
        // Fetch products
        const productsResponse = await fetch(`/api/products?locale=${locale}`);
        const productsData = await productsResponse.json();

        if (productsData.success) {
          // Separate bundles from regular products
          const bundleProducts = productsData.data.filter((p: Product) => p.category === 'bundles');
          const regularProducts = productsData.data.filter((p: Product) => p.category !== 'bundles');

          setBundles(bundleProducts);
          setProducts(regularProducts);

          // Fetch bundle configurations
          if (bundleProducts.length > 0) {
            const bundlesResponse = await fetch('/api/bundles');
            const bundlesData = await bundlesResponse.json();

            if (bundlesData.success) {
              const configs: Record<string, BundleConfiguration> = {};
              bundlesData.data.forEach((config: BundleConfiguration) => {
                configs[config.bundleProductId] = config;
              });
              setBundleConfigs(configs);
            }
          }
        }

        // Fetch categories
        const categoriesResponse = await fetch('/api/products/categories');
        const categoriesData = await categoriesResponse.json();

        if (categoriesData.success && productsData.success) {
          const prices = productsData.data.map((p: Product) => p.price);
          setFilterOptions({
            categories: categoriesData.data,
            priceRange: {
              min: Math.floor(Math.min(...prices)),
              max: Math.ceil(Math.max(...prices))
            }
          });
        }
      } catch (error) {
        console.error('Failed to fetch data:', error);
      } finally {
        setLoading(false);
      }
    };

    fetchData();
  }, [locale]);

  // Apply filters and search
  const applyFilters = useCallback(() => {
    let filtered = [...products];

    // Apply search
    if (debouncedSearchQuery) {
      const query = debouncedSearchQuery.toLowerCase();
      filtered = filtered.filter(product => {
        const name = locale === 'sv' ? product.translations.sv.name : product.translations.en.name;
        const description = locale === 'sv' ? product.translations.sv.description : product.translations.en.description;
        return (
          name.toLowerCase().includes(query) ||
          description.toLowerCase().includes(query) ||
          product.sku.toLowerCase().includes(query)
        );
      });
    }

    // Apply category filter
    if (filters.category) {
      filtered = filtered.filter(product => product.category === filters.category);
    }

    // Apply price filters
    if (filters.minPrice !== undefined) {
      filtered = filtered.filter(product => product.price >= filters.minPrice!);
    }
    if (filters.maxPrice !== undefined) {
      filtered = filtered.filter(product => product.price <= filters.maxPrice!);
    }

    // Apply stock filter
    if (filters.inStock) {
      filtered = filtered.filter(product => product.stock > 0);
    }

    // Apply sorting
    if (filters.sortBy) {
      filtered.sort((a, b) => {
        let valueA: string | number | Date;
        let valueB: string | number | Date;

        switch (filters.sortBy) {
          case 'name':
            valueA = locale === 'sv' ? a.translations.sv.name : a.translations.en.name;
            valueB = locale === 'sv' ? b.translations.sv.name : b.translations.en.name;
            break;
          case 'price':
            valueA = a.price;
            valueB = b.price;
            break;
          case 'created':
            valueA = a.createdAt;
            valueB = b.createdAt;
            break;
          default:
            valueA = a.name;
            valueB = b.name;
        }

        if (filters.sortOrder === 'desc') {
          return valueA > valueB ? -1 : valueA < valueB ? 1 : 0;
        } else {
          return valueA < valueB ? -1 : valueA > valueB ? 1 : 0;
        }
      });
    }

    setFilteredProducts(filtered);
  }, [products, debouncedSearchQuery, filters, locale]);

  useEffect(() => {
    applyFilters();
  }, [applyFilters]);

  const handleSearch = (e: React.FormEvent) => {
    e.preventDefault();
    // Search is handled by the debounced effect
  };

  if (loading) {
    return (
      <div className="container mx-auto px-4 py-8">
        <div className="animate-pulse">
          <div className="h-8 bg-cream-300 dark:bg-[#343c39] rounded w-1/4 mb-6"></div>
          <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
            <div className="h-96 bg-cream-300 dark:bg-[#343c39] rounded"></div>
            <div className="lg:col-span-3">
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
                {[...Array(6)].map((_, i) => (
                  <div key={i} className="h-96 bg-cream-300 dark:bg-[#343c39] rounded"></div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-b from-yellow-50 to-white dark:from-[#1a1f1e] dark:to-[#242a28]">
      <div className="container mx-auto px-4 py-8">
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-forest-900 dark:text-[#E8EDE8] mb-2">
            {locale === 'sv' ? 'Alla Produkter' : 'All Products'}
          </h1>
          <p className="text-forest-600 dark:text-[#B8C5B8]">
            {locale === 'sv'
              ? 'Upptäck vårt fullständiga sortiment av premium eteriska oljor och aromaterapi-produkter.'
              : 'Discover our complete range of premium essential oils and aromatherapy products.'
            }
          </p>
        </div>

        {/* Search Bar */}
        <div className="mb-6">
          <form onSubmit={handleSearch} className="relative max-w-md">
            <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
              <MagnifyingGlassIcon className="h-5 w-5 text-forest-400 dark:text-[#6B7B6B]" />
            </div>
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder={locale === 'sv' ? 'Sök produkter...' : 'Search products...'}
              className="block w-full pl-10 pr-3 py-2 border border-cream-300 dark:border-[#4a5552] rounded-md leading-5 bg-white dark:bg-[#2a3330] dark:text-[#E8EDE8] placeholder-forest-500 dark:placeholder-[#6B7B6B] focus:outline-none focus:placeholder-forest-400 focus:ring-1 focus:ring-sage-500 focus:border-sage-500"
            />
          </form>
        </div>

        {/* Bundles Section */}
        {bundles.length > 0 && (
          <div className="mb-12">
            <div className="mb-6">
              <h2 className="text-2xl font-serif font-bold text-forest-800 mb-2">
                {locale === 'sv' ? 'Spara med våra paket' : 'Save with our bundles'}
              </h2>
              <p className="text-forest-600 dark:text-[#B8C5B8]">
                {locale === 'sv'
                  ? 'Välj dina favoritoljor och spara upp till 16% jämfört med att köpa dem separat'
                  : 'Choose your favorite oils and save up to 16% compared to buying them separately'}
              </p>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {bundles.map((bundle) => {
                const config = bundleConfigs[bundle.id];
                if (!config) return null;
                return (
                  <BundleCard
                    key={bundle.id}
                    product={bundle}
                    requiredQuantity={config.requiredQuantity}
                    discountPercentage={config.discountPercentage}
                    locale={locale}
                  />
                );
              })}
            </div>
          </div>
        )}

        {/* Results Count */}
        <div className="mb-6 flex items-center justify-between">
          <p className="text-sm text-forest-700 dark:text-[#C5D4C5]">
            {locale === 'sv' 
              ? `Visar ${filteredProducts.length} av ${products.length} produkter`
              : `Showing ${filteredProducts.length} of ${products.length} products`
            }
            {debouncedSearchQuery && (
              <span className="font-medium">
                {locale === 'sv' ? ' för &quot;' : ' for &quot;'}
                {debouncedSearchQuery}&quot;
              </span>
            )}
          </p>
        </div>

        {/* Main Content */}
        <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
          {/* Filters Sidebar */}
          <div className="lg:col-span-1">
            <ProductFilters
              locale={locale}
              filters={filters}
              options={filterOptions}
              onFiltersChange={setFilters}
              className="sticky top-4"
            />
          </div>

          {/* Products Grid */}
          <div className="lg:col-span-3">
            <ProductGrid
              products={filteredProducts}
              locale={locale}
              emptyMessage={
                debouncedSearchQuery
                  ? (locale === 'sv' 
                      ? `Inga produkter hittades för "${debouncedSearchQuery}"`
                      : `No products found for "${debouncedSearchQuery}"`)
                  : (locale === 'sv' 
                      ? 'Inga produkter matchar dina filter'
                      : 'No products match your filters')
              }
            />
          </div>
        </div>
      </div>
    </div>
  );
}
